import { Item } from "../../models/item";
import handler from "../../utils/handler";

export default handler(async (event) => {
	await list.map(async (item) => {
		const type = new Item(item);
		await type.save();
	});

	return {
		length: list.length,
	};
});

const list = [
	{
		assetDescription: null,
		assetId: "qJfnKleFCUW6rlYsKEGiEA",
		assetInfo: { nickname: "Cash Test", descriptionEstatePlan: "", estimateValue: 5000, purchaseCost: 0, asOfDate: "2025-03-28T15:55:22+00:00", isFavorite: false },
		assetInfoType: "ManualCash",
		assetMask: null,
		assetName: null,
		assetOwnerName: null,
		balanceAsOf: "2025-03-28T15:55:22+00:00",
		balanceCostBasis: 0.0,
		balanceCostFrom: "UserManual",
		balanceCurrent: 5000.0,
		balanceFrom: "UserManual",
		balancePrice: null,
		balancePriceFrom: "UserManual",
		balanceQuantityCurrent: 5000.0,
		beneficiaryComposition: null,
		cognitoId: "d92f061e-a6b4-4292-97ab-3fd76d4e3442",
		creationDate: "2025-03-28T15:55:36+00:00",
		currencyCode: null,
		deactivateBy: null,
		descriptionEstatePlan: "",
		hasInvestment: null,
		holdings: null,
		includeInNetWorth: true,
		institutionId: 101,
		institutionName: null,
		integration: null,
		integrationAccountId: null,
		isActive: true,
		isAsset: true,
		isFavorite: false,
		isLinkedVendor: null,
		lastUpdate: "2025-01-01T16:55:22+00:00",
		lastUpdateAttempt: "2025-03-28T16:16:13+00:00",
		logoName: null,
		modificationDate: "2025-03-28T16:16:13+00:00",
		nextUpdate: null,
		nickname: "Cash Test",
		note: null,
		noteDate: null,
		ownership: null,
		primaryAssetCategory: "Cash",
		status: null,
		statusCode: null,
		userInstitutionId: "i7zh3OMH4UOEjbj2xuHMkw",
		vendorAccountType: null,
		vendorContainer: null,
		vendorResponse: null,
		vendorResponseType: "Other",
		wealthAssetType: "Cash",
		wid: "ae0df17e-514e-4f52-a0b5-5bfb1adf84c9",
	},
	{
		assetDescription: null,
		assetId: "4Xal3Zc5Ekq1JBeFeq8veQ",
		assetInfo: {
			manualAddType: 0,
			modelYear: 0,
			nickname: "Vehicle Test",
			descriptionEstatePlan: "",
			estimateValue: 30000,
			purchaseCost: 0,
			asOfDate: "2025-03-28T15:57:34+00:00",
			isFavorite: false,
		},
		assetInfoType: "ManualVehicle",
		assetMask: null,
		assetName: null,
		assetOwnerName: null,
		balanceAsOf: "2025-03-28T15:57:34+00:00",
		balanceCostBasis: 0.0,
		balanceCostFrom: "UserManual",
		balanceCurrent: 30000.0,
		balanceFrom: "UserManual",
		balancePrice: null,
		balancePriceFrom: "UserManual",
		balanceQuantityCurrent: null,
		beneficiaryComposition: null,
		cognitoId: "d92f061e-a6b4-4292-97ab-3fd76d4e3442",
		creationDate: "2025-03-28T15:58:22+00:00",
		currencyCode: null,
		deactivateBy: null,
		descriptionEstatePlan: "",
		hasInvestment: null,
		holdings: null,
		includeInNetWorth: true,
		institutionId: 101,
		institutionName: null,
		integration: null,
		integrationAccountId: null,
		isActive: true,
		isAsset: true,
		isFavorite: false,
		isLinkedVendor: null,
		lastUpdate: "2025-03-28T15:57:34+00:00",
		lastUpdateAttempt: "2025-03-28T18:44:34+00:00",
		logoName: null,
		modificationDate: "2025-03-28T18:44:34+00:00",
		nextUpdate: null,
		nickname: "Vehicle Test",
		note: null,
		noteDate: null,
		ownership: null,
		primaryAssetCategory: "OtherProperty",
		status: null,
		statusCode: null,
		userInstitutionId: "i7zh3OMH4UOEjbj2xuHMkw",
		vendorAccountType: null,
		vendorContainer: null,
		vendorResponse: null,
		vendorResponseType: "Other",
		wealthAssetType: "Vehicle",
		wid: "ae0df17e-514e-4f52-a0b5-5bfb1adf84c9",
	},
];
