import type { ICategoryWord } from "../api/items/words.get";

const items: ICategoryWord[] = [
	{ value: "Cloud", difficulty: 1, hint: "Fluffy Sky", category: "other" },
	{ value: "Tree", difficulty: 1, hint: "Tall, Green", category: "other" },
	{ value: "Moon", difficulty: 1, hint: "Night, Crescent", category: "other" },
	{ value: "Sun", difficulty: 1, hint: "Hot, Bright", category: "other" },
	{ value: "Star", difficulty: 1, hint: "Twinkle, Night", category: "other" },
	{ value: "Beach", difficulty: 1, hint: "Sand, Waves", category: "other" },
	{ value: "Ocean", difficulty: 1, hint: "Blue, Vast", category: "other" },
	{ value: "River", difficulty: 1, hint: "Flow, Water", category: "other" },
	{ value: "Lake", difficulty: 1, hint: "Calm Water", category: "other" },
	{ value: "Mountain", difficulty: 1, hint: "Peak, Tall", category: "other" },
	{ value: "Hill", difficulty: 1, hint: "Small Mountain", category: "other" },
	{ value: "Valley", difficulty: 1, hint: "Lowland, Between Hills", category: "other" },
	{ value: "Island", difficulty: 1, hint: "Land, Surrounded by Water", category: "other" },
	{ value: "Desert", difficulty: 1, hint: "Hot, Sand", category: "other" },
	{ value: "Forest", difficulty: 1, hint: "Trees, Dense", category: "other" },
	{ value: "Jungle", difficulty: 1, hint: "Tropical, Dense", category: "other" },
	{ value: "Cave", difficulty: 1, hint: "Dark, Underground", category: "other" },
	{ value: "Waterfall", difficulty: 1, hint: "Falling Water", category: "other" },
	{ value: "Volcano", difficulty: 1, hint: "Lava, Eruption", category: "other" },
	{ value: "Glacier", difficulty: 1, hint: "Ice, Slow Movement", category: "other" },
	{ value: "Rainbow", difficulty: 1, hint: "Colorful Arch", category: "other" },
	{ value: "Rain", difficulty: 1, hint: "Water, Falling", category: "other" },
	{ value: "Snow", difficulty: 1, hint: "Cold, Flakes", category: "other" },
	{ value: "Fog", difficulty: 1, hint: "Misty, Cloudy", category: "other" },
	{ value: "Mist", difficulty: 1, hint: "Thin Fog", category: "other" },
	{ value: "Wind", difficulty: 1, hint: "Moving Air", category: "other" },
	{ value: "Storm", difficulty: 1, hint: "Heavy Rain, Strong Wind", category: "other" },
	{ value: "Tornado", difficulty: 1, hint: "Spiral, Destructive", category: "other" },
	{ value: "Hurricane", difficulty: 1, hint: "Tropical Storm", category: "other" },
	{ value: "Thunder", difficulty: 1, hint: "Sound, Lightning", category: "other" },
	{ value: "Lightning", difficulty: 1, hint: "Electric Flash", category: "other" },
	{ value: "Earthquake", difficulty: 1, hint: "Ground Shake", category: "other" },
	{ value: "Tsunami", difficulty: 1, hint: "Giant Wave", category: "other" },
	{ value: "Avalanche", difficulty: 1, hint: "Snow, Slide", category: "other" },
	{ value: "Eclipse", difficulty: 1, hint: "Sun, Moon", category: "other" },
	{ value: "Meteor", difficulty: 1, hint: "Falling Star", category: "other" },
	{ value: "Comet", difficulty: 2, hint: "Tail, Space", category: "other" },
	{ value: "Galaxy", difficulty: 2, hint: "Stars, Universe", category: "other" },
	{ value: "Nebula", difficulty: 2, hint: "Gas, Space", category: "other" },
	{ value: "Constellation", difficulty: 2, hint: "Star Pattern", category: "other" },
	{ value: "Planet", difficulty: 2, hint: "Celestial Body", category: "other" },
	{ value: "Asteroid", difficulty: 2, hint: "Small Planet", category: "other" },
	{ value: "Spaceship", difficulty: 2, hint: "Spacecraft, Travel", category: "other" },
	{ value: "Rocket", difficulty: 2, hint: "Spacecraft, Launch", category: "other" },
	{ value: "Satellite", difficulty: 2, hint: "Orbiting Object", category: "other" },
	{ value: "Astronaut", difficulty: 2, hint: "Space Explorer", category: "other" },
	{ value: "Alien", difficulty: 2, hint: "Extraterrestrial Being", category: "other" },
	{ value: "UFO", difficulty: 2, hint: "Flying Saucer", category: "other" },
	{ value: "Robot", difficulty: 2, hint: "Machine, Automation", category: "other" },
	{ value: "Computer", difficulty: 2, hint: "Electronic Device", category: "other" },
	{ value: "Internet", difficulty: 2, hint: "Global Network", category: "other" },
	{ value: "Website", difficulty: 2, hint: "Webpage, Online", category: "other" },
	{ value: "Email", difficulty: 2, hint: "Electronic Mail", category: "other" },
	{ value: "Social Media", difficulty: 2, hint: "Online Platforms", category: "other" },
	{ value: "Search Engine", difficulty: 2, hint: "Online Search", category: "other" },
	{ value: "App", difficulty: 2, hint: "Application, Mobile", category: "other" },
	{ value: "Chair", difficulty: 2, hint: "Sitting Furniture", category: "other" },
	{ value: "Table", difficulty: 2, hint: "Surface, Furniture", category: "other" },
	{ value: "Cup", difficulty: 2, hint: "Drink Holder", category: "other" },
	{ value: "Plate", difficulty: 2, hint: "Food Holder", category: "other" },
	{ value: "Book", difficulty: 2, hint: "Reading Material", category: "other" },
	{ value: "Phone", difficulty: 2, hint: "Communication Device", category: "other" },
	{ value: "Ball", difficulty: 2, hint: "Round, Bounce", category: "other" },
	{ value: "Pen", difficulty: 2, hint: "Writing Instrument", category: "other" },
	{ value: "Key", difficulty: 2, hint: "Unlock, Access", category: "other" },
	{ value: "Watch", difficulty: 2, hint: "Timepiece, Wrist", category: "other" },
	{ value: "Mirror", difficulty: 2, hint: "Reflective Surface", category: "other" },
	{ value: "Shoe", difficulty: 2, hint: "Footwear", category: "other" },
	{ value: "Bag", difficulty: 2, hint: "Carry, Container", category: "other" },
	{ value: "Hat", difficulty: 2, hint: "Headwear, Cover", category: "other" },
	{ value: "Glasses", difficulty: 2, hint: "Eyewear, Vision", category: "other" },
	{ value: "Camera", difficulty: 2, hint: "Photography Device", category: "other" },
	{ value: "Clock", difficulty: 2, hint: "Time Display", category: "other" },
	{ value: "Lamp", difficulty: 2, hint: "Light Source", category: "other" },
	{ value: "Rope", difficulty: 2, hint: "Twine, Knot", category: "other" },
	{ value: "Scissors", difficulty: 2, hint: "Cutting Tool", category: "other" },
	{ value: "Spoon", difficulty: 2, hint: "Eating Utensil", category: "other" },
	{ value: "Fork", difficulty: 2, hint: "Eating Utensil", category: "other" },
	{ value: "Knife", difficulty: 2, hint: "Cutting Tool", category: "other" },
	{ value: "Paper", difficulty: 2, hint: "Sheet Material", category: "other" },
	{ value: "Envelope", difficulty: 2, hint: "Letter Holder", category: "other" },
	{ value: "Box", difficulty: 2, hint: "Container, Storage", category: "other" },
	{ value: "Pillow", difficulty: 2, hint: "Head Rest", category: "other" },
	{ value: "Blanket", difficulty: 2, hint: "Covering, Warmth", category: "other" },
	{ value: "Towel", difficulty: 2, hint: "Absorbent Cloth", category: "other" },
	{ value: "Bottle", difficulty: 2, hint: "Container, Liquid", category: "other" },
	{ value: "Cushion", difficulty: 2, hint: "Soft Pillow", category: "other" },
	{ value: "Curtains", difficulty: 2, hint: "Window Covering", category: "other" },
	{ value: "Rug", difficulty: 2, hint: "Floor Covering", category: "other" },
	{ value: "Vase", difficulty: 2, hint: "Flower Holder", category: "other" },
	{ value: "Cupboard", difficulty: 2, hint: "Storage Furniture", category: "other" },
	{ value: "Drawer", difficulty: 2, hint: "Storage Compartment", category: "other" },
	{ value: "Shelf", difficulty: 2, hint: "Storage Surface", category: "other" },
	{ value: "Stairs", difficulty: 2, hint: "Steps, Ascend", category: "other" },
	{ value: "Ladder", difficulty: 2, hint: "Climbing Equipment", category: "other" },
	{ value: "Bridge", difficulty: 2, hint: "Crossing Structure", category: "other" },
	{ value: "Tunnel", difficulty: 2, hint: "Underground Passage", category: "other" },
	{ value: "Road", difficulty: 2, hint: "Surface, Travel", category: "other" },
	{ value: "Path", difficulty: 2, hint: "Trail, Walkway", category: "other" },
	{ value: "Street", difficulty: 2, hint: "Urban Road", category: "other" },
	{ value: "Avenue", difficulty: 2, hint: "Wide Street", category: "other" },
	{ value: "Highway", difficulty: 2, hint: "Major Road", category: "other" },
	{ value: "Freeway", difficulty: 2, hint: "High-speed Road", category: "other" },
	{ value: "Railway", difficulty: 2, hint: "Train Tracks", category: "other" },
	{ value: "Train", difficulty: 3, hint: "Rail Transport", category: "other" },
	{ value: "Tram", difficulty: 3, hint: "Urban Transport", category: "other" },
	{ value: "Bus", difficulty: 3, hint: "Public Transport", category: "other" },
	{ value: "Car", difficulty: 3, hint: "Vehicle, Automobile", category: "other" },
	{ value: "Bicycle", difficulty: 3, hint: "Two-wheeled Transport", category: "other" },
	{ value: "Motorcycle", difficulty: 3, hint: "Two-wheeled Vehicle", category: "other" },
	{ value: "Scooter", difficulty: 3, hint: "Motorized Vehicle", category: "other" },
	{ value: "Skateboard", difficulty: 3, hint: "Rolling Board", category: "other" },
	{ value: "Roller Skates", difficulty: 3, hint: "Footwear, Wheels", category: "other" },
	{ value: "Ice Skates", difficulty: 3, hint: "Footwear, Ice", category: "other" },
	{ value: "Ski", difficulty: 3, hint: "Winter Sport", category: "other" },
	{ value: "Snowboard", difficulty: 3, hint: "Snow Sport", category: "other" },
	{ value: "Surfboard", difficulty: 3, hint: "Water Sport", category: "other" },
	{ value: "Boat", difficulty: 3, hint: "Watercraft, Float", category: "other" },
	{ value: "Ship", difficulty: 3, hint: "Large Boat", category: "other" },
	{ value: "Yacht", difficulty: 3, hint: "Luxury Boat", category: "other" },
	{ value: "Submarine", difficulty: 3, hint: "Underwater Craft", category: "other" },
	{ value: "Airplane", difficulty: 3, hint: "Aircraft, Flight", category: "other" },
	{ value: "Helicopter", difficulty: 3, hint: "Rotary Wing Aircraft", category: "other" },
	{ value: "Rocket", difficulty: 3, hint: "Spacecraft, Launch", category: "other" },
	{ value: "Spaceship", difficulty: 3, hint: "Spacecraft, Travel", category: "other" },
	{ value: "Astronaut", difficulty: 3, hint: "Space Explorer", category: "other" },
	{ value: "Alien", difficulty: 3, hint: "Extraterrestrial Being", category: "other" },
	{ value: "UFO", difficulty: 3, hint: "Flying Saucer", category: "other" },
	{ value: "Robot", difficulty: 3, hint: "Machine, Automation", category: "other" },
	{ value: "Computer", difficulty: 3, hint: "Electronic Device", category: "other" },
	{ value: "Internet", difficulty: 3, hint: "Global Network", category: "other" },
	{ value: "Website", difficulty: 3, hint: "Webpage, Online", category: "other" },
	{ value: "Email", difficulty: 3, hint: "Electronic Mail", category: "other" },
	{ value: "Social Media", difficulty: 3, hint: "Online Platforms", category: "other" },
	{ value: "Search Engine", difficulty: 3, hint: "Online Search", category: "other" },
	{ value: "App", difficulty: 3, hint: "Application, Mobile", category: "other" },
	{ value: "Chair", difficulty: 3, hint: "Sitting Furniture", category: "other" },
	{ value: "Table", difficulty: 3, hint: "Surface, Furniture", category: "other" },
	{ value: "Cup", difficulty: 3, hint: "Drink Holder", category: "other" },
	{ value: "Plate", difficulty: 3, hint: "Food Holder", category: "other" },
	{ value: "Book", difficulty: 3, hint: "Reading Material", category: "other" },
	{ value: "Phone", difficulty: 3, hint: "Communication Device", category: "other" },
	{ value: "Ball", difficulty: 3, hint: "Round, Bounce", category: "other" },
	{ value: "Pen", difficulty: 3, hint: "Writing Instrument", category: "other" },
	{ value: "Key", difficulty: 3, hint: "Unlock, Access", category: "other" },
	{ value: "Watch", difficulty: 3, hint: "Timepiece, Wrist", category: "other" },
	{ value: "Mirror", difficulty: 3, hint: "Reflective Surface", category: "other" },
	{ value: "Shoe", difficulty: 3, hint: "Footwear", category: "other" },
	{ value: "Bag", difficulty: 3, hint: "Carry, Container", category: "other" },
	{ value: "Hat", difficulty: 3, hint: "Headwear, Cover", category: "other" },
	{ value: "Glasses", difficulty: 3, hint: "Eyewear, Vision", category: "other" },
	{ value: "Camera", difficulty: 3, hint: "Photography Device", category: "other" },
	{ value: "Clock", difficulty: 3, hint: "Time Display", category: "other" },
	{ value: "Lamp", difficulty: 3, hint: "Light Source", category: "other" },
	{ value: "Wallet", difficulty: 3, hint: "Money Holder", category: "other" },
	{ value: "Remote", difficulty: 3, hint: "Control Device", category: "other" },
];

export default items;
