import type { ICategoryWord } from "../api/items/words.get";

const items: ICategoryWord[] = [
	{ value: "Paris", category: "place", difficulty: 1, hint: "Capital of France" },
	{ value: "London", category: "place", difficulty: 1, hint: "Capital of the United Kingdom" },
	{ value: "New York City", category: "place", difficulty: 1, hint: "City that never sleeps" },
	{ value: "Tokyo", category: "place", difficulty: 1, hint: "Capital of Japan" },
	{ value: "Rome", category: "place", difficulty: 1, hint: "Capital of Italy" },
	{ value: "Sydney", category: "place", difficulty: 1, hint: "Australian metropolis" },
	{ value: "Dubai", category: "place", difficulty: 1, hint: "Ultra-modern city in the desert" },
	{ value: "Los Angeles", category: "place", difficulty: 1, hint: "City of Angels" },
	{ value: "Berlin", category: "place", difficulty: 1, hint: "Capital of Germany" },
	{ value: "Madrid", category: "place", difficulty: 1, hint: "Capital of Spain" },
	{ value: "Moscow", category: "place", difficulty: 1, hint: "Capital of Russia" },
	{ value: "Beijing", category: "place", difficulty: 1, hint: "Capital of China" },
	{ value: "Toronto", category: "place", difficulty: 1, hint: "Canadian metropolis" },
	{ value: "Rio de Janeiro", category: "place", difficulty: 1, hint: "Brazilian coastal city" },
	{ value: "Amsterdam", category: "place", difficulty: 1, hint: "Famous for canals and bicycles" },
	{ value: "Venice", category: "place", difficulty: 1, hint: "City of canals" },
	{ value: "Florence", category: "place", difficulty: 1, hint: "Italian Renaissance gem" },
	{ value: "Barcelona", category: "place", difficulty: 1, hint: "Catalan capital" },
	{ value: "Prague", category: "place", difficulty: 1, hint: "City of a hundred spires" },
	{ value: "Vienna", category: "place", difficulty: 1, hint: "City of music" },
	{ value: "Budapest", category: "place", difficulty: 1, hint: "Divided by the Danube" },
	{ value: "Athens", category: "place", difficulty: 1, hint: "Birthplace of democracy" },
	{ value: "Cairo", category: "place", difficulty: 1, hint: "Egyptian capital" },
	{ value: "Seoul", category: "place", difficulty: 1, hint: "Capital of South Korea" },
	{ value: "Mumbai", category: "place", difficulty: 1, hint: "Indian financial powerhouse" },
	{ value: "Istanbul", category: "place", difficulty: 1, hint: "City on two continents" },
	{ value: "Singapore", category: "place", difficulty: 1, hint: "City-state in Southeast Asia" },
	{ value: "San Francisco", category: "place", difficulty: 1, hint: "City by the bay" },
	{ value: "Chicago", category: "place", difficulty: 1, hint: "Windy City" },
	{ value: "Washington, D.C.", category: "place", difficulty: 1, hint: "Capital of the United States" },
	{ value: "Las Vegas", category: "place", difficulty: 1, hint: "City of lights and casinos" },
	{ value: "Dublin", category: "place", difficulty: 1, hint: "Capital of Ireland" },
	{ value: "Edinburgh", category: "place", difficulty: 1, hint: "Capital of Scotland" },
	{ value: "Stockholm", category: "place", difficulty: 1, hint: "Capital of Sweden" },
	{ value: "Oslo", category: "place", difficulty: 1, hint: "Capital of Norway" },
	{ value: "Copenhagen", category: "place", difficulty: 1, hint: "Capital of Denmark" },
	{ value: "Helsinki", category: "place", difficulty: 1, hint: "Capital of Finland" },
	{ value: "Warsaw", category: "place", difficulty: 1, hint: "Capital of Poland" },
	{ value: "Krakow", category: "place", difficulty: 1, hint: "Polish cultural capital" },
	{ value: "Brussels", category: "place", difficulty: 1, hint: "Capital of Belgium" },
	{ value: "Geneva", category: "place", difficulty: 1, hint: "City of peace" },
	{ value: "Zurich", category: "place", difficulty: 1, hint: "Swiss financial center" },
	{ value: "Luxembourg", category: "place", difficulty: 1, hint: "European financial hub" },
	{ value: "Monaco", category: "place", difficulty: 1, hint: "Tiny sovereign city-state" },
	{ value: "Dubrovnik", category: "place", difficulty: 1, hint: "Game of Thrones filming location" },
	{ value: "Santorini", category: "place", difficulty: 1, hint: "Greek island paradise" },
	{ value: "Bali", category: "place", difficulty: 1, hint: "Indonesian island famous for beaches" },
	{ value: "Phuket", category: "place", difficulty: 1, hint: "Thai island destination" },
	{ value: "Maldives", category: "place", difficulty: 1, hint: "Indian Ocean paradise" },
	{ value: "Seychelles", category: "place", difficulty: 1, hint: "African island nation" },
	{ value: "Hawaii", category: "place", difficulty: 1, hint: "US state known for its islands" },
	{ value: "Fiji", category: "place", difficulty: 1, hint: "South Pacific archipelago" },
	{ value: "Bora Bora", category: "place", difficulty: 1, hint: "French Polynesian island paradise" },
	{ value: "Tahiti", category: "place", difficulty: 1, hint: "French Polynesian island" },
	{ value: "Maui", category: "place", difficulty: 1, hint: "Hawaiian island" },
	{ value: "Galapagos Islands", category: "place", difficulty: 1, hint: "Ecuadorian archipelago" },
	{ value: "Machu Picchu", category: "place", difficulty: 1, hint: "Incan archaeological site" },
	{ value: "Grand Canyon", category: "place", difficulty: 1, hint: "Iconic US natural wonder" },
	{ value: "Great Barrier Reef", category: "place", difficulty: 1, hint: "World's largest coral reef system" },
	{ value: "Victoria Falls", category: "place", difficulty: 1, hint: "Waterfall in southern Africa" },
	{ value: "Niagara Falls", category: "place", difficulty: 1, hint: "Famous waterfall on the US-Canada border" },
	{ value: "Mount Everest", category: "place", difficulty: 1, hint: "World's tallest mountain" },
	{ value: "Amazon Rainforest", category: "place", difficulty: 1, hint: "Largest rainforest in the world" },
	{ value: "Sahara Desert", category: "place", difficulty: 1, hint: "World's largest hot desert" },
	{ value: "Antarctica", category: "place", difficulty: 1, hint: "Continent at the South Pole" },
	{ value: "Cape Town", category: "place", difficulty: 2, hint: "South African coastal city" },
	{ value: "Johannesburg", category: "place", difficulty: 2, hint: "South African economic hub" },
	{ value: "Nairobi", category: "place", difficulty: 2, hint: "Kenyan capital" },
	{ value: "Marrakech", category: "place", difficulty: 2, hint: "Moroccan cultural hub" },
	{ value: "Cape Verde", category: "place", difficulty: 2, hint: "African island nation" },
	{ value: "Iceland", category: "place", difficulty: 2, hint: "Northern European island nation" },
	{ value: "Belfast", category: "place", difficulty: 2, hint: "Capital of Northern Ireland" },
	{ value: "Cardiff", category: "place", difficulty: 2, hint: "Capital of Wales" },
	{ value: "Manchester", category: "place", difficulty: 2, hint: "Major city in northern England" },
	{ value: "Glasgow", category: "place", difficulty: 2, hint: "Scottish city" },
	{ value: "Liverpool", category: "place", difficulty: 2, hint: "City famous for The Beatles" },
	{ value: "Birmingham", category: "place", difficulty: 2, hint: "Major city in the West Midlands" },
	{ value: "Leeds", category: "place", difficulty: 2, hint: "City in West Yorkshire, England" },
	{ value: "Bristol", category: "place", difficulty: 2, hint: "City in South West England" },
	{ value: "Newcastle", category: "place", difficulty: 2, hint: "City on the River Tyne" },
	{ value: "Sheffield", category: "place", difficulty: 2, hint: "City in South Yorkshire, England" },
	{ value: "Brighton", category: "place", difficulty: 2, hint: "Seaside resort town" },
	{ value: "Oxford", category: "place", difficulty: 2, hint: "Famous university city" },
	{ value: "Cambridge", category: "place", difficulty: 2, hint: "Famous university city" },
	{ value: "York", category: "place", difficulty: 2, hint: "Historic city in Yorkshire, England" },
	{ value: "Bath", category: "place", difficulty: 2, hint: "City famous for Roman-built baths" },
	{ value: "Canterbury", category: "place", difficulty: 2, hint: "Famous cathedral city" },
	{ value: "Durham", category: "place", difficulty: 2, hint: "City with a famous cathedral" },
	{ value: "Norwich", category: "place", difficulty: 2, hint: "City in East Anglia, England" },
	{ value: "Nottingham", category: "place", difficulty: 2, hint: "City famous for Robin Hood" },
	{ value: "Leicester", category: "place", difficulty: 2, hint: "City in the East Midlands" },
	{ value: "Southampton", category: "place", difficulty: 2, hint: "Port city on the south coast of England" },
	{ value: "Portsmouth", category: "place", difficulty: 2, hint: "Port city in Hampshire, England" },
	{ value: "Exeter", category: "place", difficulty: 2, hint: "City in Devon, England" },
	{ value: "Plymouth", category: "place", difficulty: 2, hint: "City in Devon, England" },
	{ value: "Cornwall", category: "place", difficulty: 2, hint: "County in southwestern England" },
	{ value: "Isle of Wight", category: "place", difficulty: 2, hint: "Island in the English Channel" },
	{ value: "Channel Islands", category: "place", difficulty: 2, hint: "British Crown dependencies in the English Channel" },
	{ value: "Jersey", category: "place", difficulty: 2, hint: "Largest of the Channel Islands" },
	{ value: "Guernsey", category: "place", difficulty: 2, hint: "Channel Island with its own government" },
	{ value: "Isle of Man", category: "place", difficulty: 2, hint: "Self-governing British Crown dependency" },
	{ value: "Faroe Islands", category: "place", difficulty: 2, hint: "North Atlantic archipelago" },
	{ value: "Ibiza", category: "place", difficulty: 2, hint: "Spanish island known for its nightlife" },
	{ value: "Majorca", category: "place", difficulty: 2, hint: "Spanish island in the Mediterranean" },
	{ value: "Menorca", category: "place", difficulty: 2, hint: "Spanish Balearic island" },
	{ value: "Tenerife", category: "place", difficulty: 2, hint: "Largest of the Canary Islands" },
	{ value: "Gran Canaria", category: "place", difficulty: 2, hint: "Canary Island known for beaches and resorts" },
	{ value: "Fuerteventura", category: "place", difficulty: 2, hint: "Canary Island known for windsurfing" },
	{ value: "Lanzarote", category: "place", difficulty: 2, hint: "Canary Island known for volcanic landscapes" },
	{ value: "La Palma", category: "place", difficulty: 2, hint: "Canary Island with diverse landscapes" },
	{ value: "La Gomera", category: "place", difficulty: 2, hint: "Canary Island with lush forests" },
	{ value: "El Hierro", category: "place", difficulty: 2, hint: "Smallest of the Canary Islands" },
	{ value: "Sicily", category: "place", difficulty: 2, hint: "Italian island in the Mediterranean" },
	{ value: "Sardinia", category: "place", difficulty: 2, hint: "Italian island known for beaches and archaeology" },
	{ value: "Corsica", category: "place", difficulty: 2, hint: "French island in the Mediterranean" },
	{ value: "Malta", category: "place", difficulty: 2, hint: "Mediterranean island nation" },
	{ value: "Crete", category: "place", difficulty: 2, hint: "Greek island with ancient ruins" },
	{ value: "Rhodes", category: "place", difficulty: 2, hint: "Greek island with medieval history" },
	{ value: "Corfu", category: "place", difficulty: 2, hint: "Greek island known for its beaches" },
	{ value: "Mykonos", category: "place", difficulty: 2, hint: "Greek island known for nightlife" },
	{ value: "Paros", category: "place", difficulty: 2, hint: "Greek island in the Aegean Sea" },
	{ value: "Naxos", category: "place", difficulty: 2, hint: "Greek island in the Cyclades" },
	{ value: "Ios", category: "place", difficulty: 2, hint: "Greek island known for parties and beaches" },
	{ value: "Syros", category: "place", difficulty: 2, hint: "Greek island with neoclassical architecture" },
	{ value: "Delos", category: "place", difficulty: 2, hint: "Greek island with archaeological sites" },
	{ value: "Patmos", category: "place", difficulty: 2, hint: "Greek island known for its religious significance" },
	{ value: "Chios", category: "place", difficulty: 2, hint: "Greek island known for mastic production" },
	{ value: "Lesbos", category: "place", difficulty: 2, hint: "Greek island known for its natural beauty" },
	{ value: "Samos", category: "place", difficulty: 2, hint: "Greek island known for its wine" },
	{ value: "Kos", category: "place", difficulty: 2, hint: "Greek island known for ancient ruins" },
	{ value: "Kalymnos", category: "place", difficulty: 2, hint: "Greek island known for rock climbing" },
	{ value: "Leros", category: "place", difficulty: 2, hint: "Greek island known for its quiet beaches" },
	{ value: "Kastellorizo", category: "place", difficulty: 2, hint: "Greek island near Turkey" },
	{ value: "Thessaloniki", category: "place", difficulty: 2, hint: "Second-largest city in Greece" },
	{ value: "Reykjavik", category: "place", difficulty: 3, hint: "Capital of Iceland" },
	{ value: "Bern", category: "place", difficulty: 3, hint: "Capital of Switzerland" },
	{ value: "Bratislava", category: "place", difficulty: 3, hint: "Capital of Slovakia" },
	{ value: "Belgrade", category: "place", difficulty: 3, hint: "Capital of Serbia" },
	{ value: "Sarajevo", category: "place", difficulty: 3, hint: "Capital of Bosnia and Herzegovina" },
	{ value: "Zagreb", category: "place", difficulty: 3, hint: "Capital of Croatia" },
	{ value: "Ljubljana", category: "place", difficulty: 3, hint: "Capital of Slovenia" },
	{ value: "Sofia", category: "place", difficulty: 3, hint: "Capital of Bulgaria" },
	{ value: "Bucharest", category: "place", difficulty: 3, hint: "Capital of Romania" },
	{ value: "Chisinau", category: "place", difficulty: 3, hint: "Capital of Moldova" },
	{ value: "Tirana", category: "place", difficulty: 3, hint: "Capital of Albania" },
	{ value: "Podgorica", category: "place", difficulty: 3, hint: "Capital of Montenegro" },
	{ value: "Skopje", category: "place", difficulty: 3, hint: "Capital of North Macedonia" },
	{ value: "Tallinn", category: "place", difficulty: 3, hint: "Capital of Estonia" },
	{ value: "Riga", category: "place", difficulty: 3, hint: "Capital of Latvia" },
	{ value: "Vilnius", category: "place", difficulty: 3, hint: "Capital of Lithuania" },
	{ value: "Minsk", category: "place", difficulty: 3, hint: "Capital of Belarus" },
	{ value: "Astana", category: "place", difficulty: 3, hint: "Former capital of Kazakhstan" },
	{ value: "Ashgabat", category: "place", difficulty: 3, hint: "Capital of Turkmenistan" },
	{ value: "Tashkent", category: "place", difficulty: 3, hint: "Capital of Uzbekistan" },
	{ value: "Bishkek", category: "place", difficulty: 3, hint: "Capital of Kyrgyzstan" },
	{ value: "Dushanbe", category: "place", difficulty: 3, hint: "Capital of Tajikistan" },
	{ value: "Yerevan", category: "place", difficulty: 3, hint: "Capital of Armenia" },
	{ value: "Tbilisi", category: "place", difficulty: 3, hint: "Capital of Georgia" },
	{ value: "Baku", category: "place", difficulty: 3, hint: "Capital of Azerbaijan" },
	{ value: "Ankara", category: "place", difficulty: 3, hint: "Capital of Turkey" },
	{ value: "Baghdad", category: "place", difficulty: 3, hint: "Capital of Iraq" },
	{ value: "Jerusalem", category: "place", difficulty: 3, hint: "Capital of Israel" },
	{ value: "Beirut", category: "place", difficulty: 3, hint: "Capital of Lebanon" },
	{ value: "Damascus", category: "place", difficulty: 3, hint: "Capital of Syria" },
	{ value: "Amman", category: "place", difficulty: 3, hint: "Capital of Jordan" },
	{ value: "Kuwait City", category: "place", difficulty: 3, hint: "Capital of Kuwait" },
	{ value: "Manama", category: "place", difficulty: 3, hint: "Capital of Bahrain" },
	{ value: "Doha", category: "place", difficulty: 3, hint: "Capital of Qatar" },
	{ value: "Abu Dhabi", category: "place", difficulty: 3, hint: "Capital of the United Arab Emirates" },
	{ value: "Muscat", category: "place", difficulty: 3, hint: "Capital of Oman" },
	{ value: "Sana'a", category: "place", difficulty: 3, hint: "Capital of Yemen" },
	{ value: "Riyadh", category: "place", difficulty: 3, hint: "Capital of Saudi Arabia" },
	{ value: "Tehran", category: "place", difficulty: 3, hint: "Capital of Iran" },
	{ value: "Kabul", category: "place", difficulty: 3, hint: "Capital of Afghanistan" },
	{ value: "Islamabad", category: "place", difficulty: 3, hint: "Capital of Pakistan" },
	{ value: "Kathmandu", category: "place", difficulty: 3, hint: "Capital of Nepal" },
	{ value: "Thimphu", category: "place", difficulty: 3, hint: "Capital of Bhutan" },
	{ value: "Colombo", category: "place", difficulty: 3, hint: "Capital of Sri Lanka" },
	{ value: "Male", category: "place", difficulty: 3, hint: "Capital of Maldives" },
	{ value: "Dhaka", category: "place", difficulty: 3, hint: "Capital of Bangladesh" },
	{ value: "Naypyidaw", category: "place", difficulty: 3, hint: "Capital of Myanmar" },
	{ value: "Bangkok", category: "place", difficulty: 3, hint: "Capital of Thailand" },
	{ value: "Hanoi", category: "place", difficulty: 3, hint: "Capital of Vietnam" },
	{ value: "Phnom Penh", category: "place", difficulty: 3, hint: "Capital of Cambodia" },
	{ value: "Vientiane", category: "place", difficulty: 3, hint: "Capital of Laos" },
	{ value: "Jakarta", category: "place", difficulty: 3, hint: "Capital of Indonesia" },
	{ value: "Kuala Lumpur", category: "place", difficulty: 3, hint: "Capital of Malaysia" },
	{ value: "Bandar Seri Begawan", category: "place", difficulty: 3, hint: "Capital of Brunei" },
	{ value: "Dili", category: "place", difficulty: 3, hint: "Capital of East Timor" },
	{ value: "Port Moresby", category: "place", difficulty: 3, hint: "Capital of Papua New Guinea" },
	{ value: "Ngerulmud", category: "place", difficulty: 3, hint: "Capital of Palau" },
	{ value: "Honiara", category: "place", difficulty: 3, hint: "Capital of Solomon Islands" },
	{ value: "Palikir", category: "place", difficulty: 3, hint: "Capital of Micronesia" },
	{ value: "Suva", category: "place", difficulty: 3, hint: "Capital of Fiji" },
	{ value: "Apia", category: "place", difficulty: 3, hint: "Capital of Samoa" },
	{ value: "Nuku'alofa", category: "place", difficulty: 3, hint: "Capital of Tonga" },
	{ value: "Funafuti", category: "place", difficulty: 3, hint: "Capital of Tuvalu" },
	{ value: "Majuro", category: "place", difficulty: 3, hint: "Capital of Marshall Islands" },
];

export default items;
