import type { ICategoryWord } from "../api/items/words.get";

const items: ICategoryWord[] = [
	{ value: "Happy", category: "emotion", difficulty: 1, hint: "Positive feeling" },
	{ value: "Sad", category: "emotion", difficulty: 1, hint: "Negative feeling" },
	{ value: "Angry", category: "emotion", difficulty: 1, hint: "Strong displeasure" },
	{ value: "Excited", category: "emotion", difficulty: 1, hint: "Eager anticipation" },
	{ value: "Scared", category: "emotion", difficulty: 1, hint: "Feeling of fear" },
	{ value: "Surprised", category: "emotion", difficulty: 1, hint: "Caught off guard" },
	{ value: "Tired", category: "emotion", difficulty: 1, hint: "Feeling of fatigue" },
	{ value: "Relaxed", category: "emotion", difficulty: 1, hint: "Calm and unwound" },
	{ value: "Calm", category: "emotion", difficulty: 1, hint: "Peaceful state" },
	{ value: "Content", category: "emotion", difficulty: 1, hint: "Satisfied and happy" },
	{ value: "Nervous", category: "emotion", difficulty: 1, hint: "Feeling uneasy" },
	{ value: "Bored", category: "emotion", difficulty: 1, hint: "Lacking interest" },
	{ value: "Curious", category: "emotion", difficulty: 1, hint: "Eager to know" },
	{ value: "Confused", category: "emotion", difficulty: 1, hint: "Lack of understanding" },
	{ value: "Proud", category: "emotion", difficulty: 1, hint: "Feeling of accomplishment" },
	{ value: "Shy", category: "emotion", difficulty: 1, hint: "Reserved or timid" },
	{ value: "Embarrassed", category: "emotion", difficulty: 1, hint: "Feeling self-conscious" },
	{ value: "Grateful", category: "emotion", difficulty: 1, hint: "Thankful and appreciative" },
	{ value: "Hopeful", category: "emotion", difficulty: 1, hint: "Feeling optimism" },
	{ value: "Loving", category: "emotion", difficulty: 1, hint: "Affectionate and caring" },
	{ value: "Jealous", category: "emotion", difficulty: 1, hint: "Feeling envious" },
	{ value: "Envious", category: "emotion", difficulty: 1, hint: "Desiring what others have" },
	{ value: "Guilty", category: "emotion", difficulty: 1, hint: "Feeling remorse" },
	{ value: "Joyful", category: "emotion", difficulty: 1, hint: "Full of joy" },
	{ value: "Lonely", category: "emotion", difficulty: 1, hint: "Feeling isolated" },
	{ value: "Satisfied", category: "emotion", difficulty: 1, hint: "Feeling content" },
	{ value: "Anxious", category: "emotion", difficulty: 1, hint: "Feeling uneasy" },
	{ value: "Impatient", category: "emotion", difficulty: 1, hint: "Lacking patience" },
	{ value: "Disappointed", category: "emotion", difficulty: 1, hint: "Feeling let down" },
	{ value: "Frustrated", category: "emotion", difficulty: 1, hint: "Feeling annoyed" },
	{ value: "Overwhelmed", category: "emotion", difficulty: 1, hint: "Feeling swamped" },
	{ value: "Optimistic", category: "emotion", difficulty: 1, hint: "Feeling hopeful" },
	{ value: "Pessimistic", category: "emotion", difficulty: 1, hint: "Expecting the worst" },
	{ value: "Inferior", category: "emotion", difficulty: 1, hint: "Feeling lower in status" },
	{ value: "Superior", category: "emotion", difficulty: 1, hint: "Feeling higher in status" },
	{ value: "Inspired", category: "emotion", difficulty: 1, hint: "Feeling motivated" },
	{ value: "Motivated", category: "emotion", difficulty: 1, hint: "Feeling driven" },
	{ value: "Indifferent", category: "emotion", difficulty: 1, hint: "Lacking concern" },
	{ value: "Regretful", category: "emotion", difficulty: 1, hint: "Feeling remorse" },
	{ value: "Remorseful", category: "emotion", difficulty: 1, hint: "Feeling regret" },
	{ value: "Resentful", category: "emotion", difficulty: 1, hint: "Feeling bitter" },
	{ value: "Defensive", category: "emotion", difficulty: 1, hint: "Feeling protective" },
	{ value: "Hostile", category: "emotion", difficulty: 1, hint: "Feeling aggressive" },
	{ value: "Vengeful", category: "emotion", difficulty: 1, hint: "Feeling retaliatory" },
	{ value: "Forgiving", category: "emotion", difficulty: 1, hint: "Willing to pardon" },
	{ value: "Forgetful", category: "emotion", difficulty: 1, hint: "Lacking memory" },
	{ value: "Reminiscent", category: "emotion", difficulty: 1, hint: "Feeling nostalgic" },
	{ value: "Reflective", category: "emotion", difficulty: 1, hint: "Thoughtful introspection" },
	{ value: "Introspective", category: "emotion", difficulty: 1, hint: "Self-analysis" },
	{ value: "Thoughtful", category: "emotion", difficulty: 1, hint: "Considerate and contemplative" },
	{ value: "Selfish", category: "emotion", difficulty: 1, hint: "Lacking generosity" },
	{ value: "Selfless", category: "emotion", difficulty: 1, hint: "Putting others first" },
	{ value: "Generous", category: "emotion", difficulty: 1, hint: "Willing to give" },
	{ value: "Greedy", category: "emotion", difficulty: 1, hint: "Excessively desiring" },
	{ value: "Materialistic", category: "emotion", difficulty: 1, hint: "Valuing possessions" },
	{ value: "Altruistic", category: "emotion", difficulty: 1, hint: "Selflessly concerned" },
	{ value: "Egotistical", category: "emotion", difficulty: 1, hint: "Self-centered" },
	{ value: "Humble", category: "emotion", difficulty: 1, hint: "Modest and unassuming" },
	{ value: "Arrogant", category: "emotion", difficulty: 1, hint: "Overbearingly proud" },
	{ value: "Confident", category: "emotion", difficulty: 1, hint: "Assured and self-reliant" },
	{ value: "Insecure", category: "emotion", difficulty: 1, hint: "Lacking confidence" },
	{ value: "Courageous", category: "emotion", difficulty: 1, hint: "Bold and brave" },
	{ value: "Cowardly", category: "emotion", difficulty: 1, hint: "Lacking courage" },
	{ value: "Brave", category: "emotion", difficulty: 1, hint: "Fearless and valiant" },
	{ value: "Fearful", category: "emotion", difficulty: 1, hint: "Feeling afraid" },
	{ value: "Determined", category: "emotion", difficulty: 1, hint: "Strongly motivated" },
	{ value: "Indecisive", category: "emotion", difficulty: 1, hint: "Lacking decisiveness" },
	{ value: "Decisive", category: "emotion", difficulty: 1, hint: "Able to make decisions" },
	{ value: "Resolute", category: "emotion", difficulty: 1, hint: "Determined and unwavering" },
	{ value: "Hesitant", category: "emotion", difficulty: 1, hint: "Uncertain or hesitant" },
	{ value: "Persistent", category: "emotion", difficulty: 1, hint: "Continuing despite obstacles" },
	{ value: "Resilient", category: "emotion", difficulty: 1, hint: "Able to recover quickly" },
	{ value: "Vulnerable", category: "emotion", difficulty: 1, hint: "Open to harm" },
	{ value: "Invincible", category: "emotion", difficulty: 1, hint: "Unbeatable and unbeatable" },
	{ value: "Defeated", category: "emotion", difficulty: 1, hint: "Feeling beaten" },
	{ value: "Triumphant", category: "emotion", difficulty: 1, hint: "Feeling victorious" },
	{ value: "Victorious", category: "emotion", difficulty: 1, hint: "Achieving success" },
	{ value: "Successful", category: "emotion", difficulty: 1, hint: "Achieving goals" },
	{ value: "Unsuccessful", category: "emotion", difficulty: 1, hint: "Failing to achieve" },
	{ value: "Accomplished", category: "emotion", difficulty: 1, hint: "Achieving success" },
	{ value: "Worthless", category: "emotion", difficulty: 1, hint: "Feeling insignificant" },
	{ value: "Valuable", category: "emotion", difficulty: 1, hint: "Feeling worthy" },
	{ value: "Useless", category: "emotion", difficulty: 1, hint: "Not serving a purpose" },
	{ value: "Hopeless", category: "emotion", difficulty: 1, hint: "Feeling despair" },
	{ value: "Despair", category: "emotion", difficulty: 1, hint: "Complete loss of hope" },
	{ value: "Desperation", category: "emotion", difficulty: 1, hint: "Feeling of hopelessness" },
	{ value: "Acceptance", category: "emotion", difficulty: 1, hint: "Acknowledging reality" },
	{ value: "Denial", category: "emotion", difficulty: 1, hint: "Refusing to accept" },
	{ value: "Skepticism", category: "emotion", difficulty: 1, hint: "Doubtful attitude" },
	{ value: "Belief", category: "emotion", difficulty: 1, hint: "Holding convictions" },
	{ value: "Faith", category: "emotion", difficulty: 1, hint: "Trust and confidence" },
	{ value: "Ecstatic", category: "emotion", difficulty: 2, hint: "Extreme joy" },
	{ value: "Melancholic", category: "emotion", difficulty: 2, hint: "Feeling of sadness" },
	{ value: "Rageful", category: "emotion", difficulty: 2, hint: "Intense anger" },
	{ value: "Terrified", category: "emotion", difficulty: 2, hint: "Extreme fear" },
	{ value: "Astonished", category: "emotion", difficulty: 2, hint: "Amazed and surprised" },
	{ value: "Exhausted", category: "emotion", difficulty: 2, hint: "Drained of energy" },
	{ value: "Soothing", category: "emotion", difficulty: 2, hint: "Calming and relaxing" },
	{ value: "Tranquil", category: "emotion", difficulty: 2, hint: "Peaceful and serene" },
	{ value: "Serene", category: "emotion", difficulty: 2, hint: "Calm and peaceful" },
	{ value: "Blissful", category: "emotion", difficulty: 2, hint: "Feeling of happiness" },
	{ value: "Pensive", category: "emotion", difficulty: 2, hint: "Thoughtfully reflective" },
	{ value: "Perplexed", category: "emotion", difficulty: 2, hint: "Confused and puzzled" },
	{ value: "Elated", category: "emotion", difficulty: 2, hint: "Extremely happy" },
	{ value: "Isolated", category: "emotion", difficulty: 2, hint: "Feeling alone" },
	{ value: "Contented", category: "emotion", difficulty: 2, hint: "Feeling satisfied" },
	{ value: "Restless", category: "emotion", difficulty: 2, hint: "Unable to relax" },
	{ value: "Agitated", category: "emotion", difficulty: 2, hint: "Feeling irritated" },
	{ value: "Fulfilled", category: "emotion", difficulty: 2, hint: "Satisfied and content" },
	{ value: "Intrigued", category: "emotion", difficulty: 2, hint: "Curious and interested" },
	{ value: "Amused", category: "emotion", difficulty: 2, hint: "Entertained and delighted" },
	{ value: "Despondent", category: "emotion", difficulty: 2, hint: "Feeling hopeless" },
	{ value: "Impassive", category: "emotion", difficulty: 2, hint: "Showing no emotion" },
	{ value: "Rebellious", category: "emotion", difficulty: 2, hint: "Defiant and resistant" },
	{ value: "Enraged", category: "emotion", difficulty: 2, hint: "Extremely angry" },
	{ value: "Overjoyed", category: "emotion", difficulty: 2, hint: "Extremely happy" },
	{ value: "Impassioned", category: "emotion", difficulty: 2, hint: "Filled with passion" },
	{ value: "Enchanted", category: "emotion", difficulty: 2, hint: "Magically delighted" },
	{ value: "Detached", category: "emotion", difficulty: 2, hint: "Emotionally disconnected" },
	{ value: "Tempted", category: "emotion", difficulty: 2, hint: "Feeling enticed" },
	{ value: "Stunned", category: "emotion", difficulty: 2, hint: "Feeling shocked" },
	{ value: "Jubilant", category: "emotion", difficulty: 2, hint: "Feeling triumphant" },
	{ value: "Cheerful", category: "emotion", difficulty: 2, hint: "Happy and optimistic" },
	{ value: "Enthusiastic", category: "emotion", difficulty: 2, hint: "Eager and excited" },
	{ value: "Aggressive", category: "emotion", difficulty: 2, hint: "Hostile and forceful" },
	{ value: "Inquisitive", category: "emotion", difficulty: 2, hint: "Curious and questioning" },
	{ value: "Surly", category: "emotion", difficulty: 2, hint: "Bad-tempered and unfriendly" },
	{ value: "Apprehensive", category: "emotion", difficulty: 2, hint: "Anxious and fearful" },
	{ value: "Rancorous", category: "emotion", difficulty: 2, hint: "Bitter and resentful" },
	{ value: "Obstinate", category: "emotion", difficulty: 2, hint: "Stubborn and inflexible" },
	{ value: "Ingratiating", category: "emotion", difficulty: 2, hint: "Trying to please" },
	{ value: "Inattentive", category: "emotion", difficulty: 2, hint: "Not paying attention" },
	{ value: "Recalcitrant", category: "emotion", difficulty: 2, hint: "Stubbornly resistant" },
	{ value: "Dejected", category: "emotion", difficulty: 2, hint: "Sad and dispirited" },
	{ value: "Irresolute", category: "emotion", difficulty: 2, hint: "Indecisive and uncertain" },
	{ value: "Ebullient", category: "emotion", difficulty: 2, hint: "Overflowing with enthusiasm" },
	{ value: "Elusive", category: "emotion", difficulty: 2, hint: "Difficult to grasp" },
	{ value: "Apologetic", category: "emotion", difficulty: 2, hint: "Expressing regret" },
	{ value: "Nostalgic", category: "emotion", difficulty: 2, hint: "Longing for the past" },
	{ value: "Defiant", category: "emotion", difficulty: 2, hint: "Boldly resistant" },
	{ value: "Desperate", category: "emotion", difficulty: 2, hint: "Feeling hopeless" },
	{ value: "Elaborate", category: "emotion", difficulty: 2, hint: "Detailed and intricate" },
	{ value: "Eloquent", category: "emotion", difficulty: 2, hint: "Expressive and articulate" },
	{ value: "Flippant", category: "emotion", difficulty: 2, hint: "Casual and disrespectful" },
	{ value: "Lighthearted", category: "emotion", difficulty: 2, hint: "Cheerful and carefree" },
	{ value: "Macabre", category: "emotion", difficulty: 2, hint: "Gruesome and disturbing" },
	{ value: "Oblivious", category: "emotion", difficulty: 2, hint: "Unaware and unconscious" },
	{ value: "Preoccupied", category: "emotion", difficulty: 2, hint: "Lost in thought" },
	{ value: "Quizzical", category: "emotion", difficulty: 2, hint: "Expressing confusion" },
	{ value: "Reticent", category: "emotion", difficulty: 2, hint: "Reserved and silent" },
	{ value: "Shameful", category: "emotion", difficulty: 2, hint: "Feeling disgrace" },
	{ value: "Yearning", category: "emotion", difficulty: 2, hint: "Longing and craving" },
	{ value: "Zealous", category: "emotion", difficulty: 2, hint: "Passionate and fervent" },
	{ value: "Exuberant", category: "emotion", difficulty: 3, hint: "Overflowing with joy" },
	{ value: "Depressed", category: "emotion", difficulty: 3, hint: "Feeling of deep sadness" },
	{ value: "Irritated", category: "emotion", difficulty: 3, hint: "Annoyed and agitated" },
	{ value: "Dumbfounded", category: "emotion", difficulty: 3, hint: "Speechless with astonishment" },
	{ value: "Fatigued", category: "emotion", difficulty: 3, hint: "Extremely tired" },
	{ value: "Composed", category: "emotion", difficulty: 3, hint: "Calm and collected" },
	{ value: "Euphoric", category: "emotion", difficulty: 3, hint: "Intensely happy" },
	{ value: "Contemplative", category: "emotion", difficulty: 3, hint: "Thoughtfully reflective" },
	{ value: "Baffled", category: "emotion", difficulty: 3, hint: "Utterly confused" },
	{ value: "Anguished", category: "emotion", difficulty: 3, hint: "Suffering intense pain" },
	{ value: "Apathetic", category: "emotion", difficulty: 3, hint: "Lacking interest or concern" },
	{ value: "Melancholy", category: "emotion", difficulty: 3, hint: "Deeply sad" },
	{ value: "Distraught", category: "emotion", difficulty: 3, hint: "Deeply troubled" },
	{ value: "Vexed", category: "emotion", difficulty: 3, hint: "Annoyed and frustrated" },
	{ value: "Horrified", category: "emotion", difficulty: 3, hint: "Filled with horror" },
	{ value: "Discombobulated", category: "emotion", difficulty: 3, hint: "Confused and disoriented" },
	{ value: "Disconsolate", category: "emotion", difficulty: 3, hint: "Unconsolably sad" },
	{ value: "Perturbed", category: "emotion", difficulty: 3, hint: "Bothered and unsettled" },
	{ value: "Afflicted", category: "emotion", difficulty: 3, hint: "Suffering and distressed" },
	{ value: "Aghast", category: "emotion", difficulty: 3, hint: "Horrified and shocked" },
	{ value: "Hysterical", category: "emotion", difficulty: 3, hint: "Wildly emotional" },
	{ value: "Disquieted", category: "emotion", difficulty: 3, hint: "Uneasily disturbed" },
	{ value: "Discomfited", category: "emotion", difficulty: 3, hint: "Feeling discomfort" },
	{ value: "Frenzied", category: "emotion", difficulty: 3, hint: "Frantically excited" },
	{ value: "Disquiet", category: "emotion", difficulty: 3, hint: "Feeling uneasy" },
	{ value: "Resigned", category: "emotion", difficulty: 3, hint: "Accepting defeat" },
	{ value: "Incredulous", category: "emotion", difficulty: 3, hint: "Unbelieving and skeptical" },
	{ value: "Dispirited", category: "emotion", difficulty: 3, hint: "Losing spirit" },
	{ value: "Disconcerted", category: "emotion", difficulty: 3, hint: "Disturbed and unsettled" },
	{ value: "Disrupted", category: "emotion", difficulty: 3, hint: "Interrupted and disturbed" },
	{ value: "Disarrayed", category: "emotion", difficulty: 3, hint: "In disarray" },
	{ value: "Dismayed", category: "emotion", difficulty: 3, hint: "Feeling disappointed" },
	{ value: "Displeased", category: "emotion", difficulty: 3, hint: "Feeling displeased" },
	{ value: "Dissatisfied", category: "emotion", difficulty: 3, hint: "Feeling unsatisfied" },
	{ value: "Dissonant", category: "emotion", difficulty: 3, hint: "Clashing and discordant" },
	{ value: "Distressed", category: "emotion", difficulty: 3, hint: "Feeling troubled" },
	{ value: "Disengaged", category: "emotion", difficulty: 3, hint: "Uninvolved and detached" },
	{ value: "Dislodged", category: "emotion", difficulty: 3, hint: "Moved or removed from place" },
	{ value: "Discontented", category: "emotion", difficulty: 3, hint: "Feeling unsatisfied" },
	{ value: "Disenchanted", category: "emotion", difficulty: 3, hint: "Feeling disillusioned" },
	{ value: "Disaffiliated", category: "emotion", difficulty: 3, hint: "Disconnected from group" },
	{ value: "Disaffirmed", category: "emotion", difficulty: 3, hint: "Denied and rejected" },
	{ value: "Disinterested", category: "emotion", difficulty: 3, hint: "Lacking interest" },
	{ value: "Disinfected", category: "emotion", difficulty: 3, hint: "Cleaned and sanitized" },
	{ value: "Disinvested", category: "emotion", difficulty: 3, hint: "Withdrawn investment" },
	{ value: "Disordered", category: "emotion", difficulty: 3, hint: "Messy and chaotic" },
	{ value: "Disorganized", category: "emotion", difficulty: 3, hint: "Lacking organization" },
	{ value: "Disinherited", category: "emotion", difficulty: 3, hint: "Deprived of inheritance" },
	{ value: "Disgraced", category: "emotion", difficulty: 3, hint: "Shamed and humiliated" },
	{ value: "Disbanded", category: "emotion", difficulty: 3, hint: "Broken up and dissolved" },
	{ value: "Disunited", category: "emotion", difficulty: 3, hint: "Not united" },
	{ value: "Dissociated", category: "emotion", difficulty: 3, hint: "Disconnected and separated" },
	{ value: "Disdained", category: "emotion", difficulty: 3, hint: "Scorned and rejected" },
	{ value: "Disdainful", category: "emotion", difficulty: 3, hint: "Showing contempt" },
	{ value: "Disillusioned", category: "emotion", difficulty: 3, hint: "Feeling disillusioned" },
	{ value: "Disempowered", category: "emotion", difficulty: 3, hint: "Feeling powerless" },
	{ value: "Displaced", category: "emotion", difficulty: 3, hint: "Forcibly moved" },
	{ value: "Disrespected", category: "emotion", difficulty: 3, hint: "Lacking respect" },
	{ value: "Disaffected", category: "emotion", difficulty: 3, hint: "Dissatisfied and rebellious" },
	{ value: "Disgruntled", category: "emotion", difficulty: 3, hint: "Discontented and annoyed" },
	{ value: "Disgusted", category: "emotion", difficulty: 3, hint: "Feeling revulsion" },
	{ value: "Disheartened", category: "emotion", difficulty: 3, hint: "Feeling discouraged" },
	{ value: "Disheveled", category: "emotion", difficulty: 3, hint: "Messy and untidy" },
	{ value: "Dishonored", category: "emotion", difficulty: 3, hint: "Shamed and disgraced" },
	{ value: "Disharmonious", category: "emotion", difficulty: 3, hint: "Lacking harmony" },
	{ value: "Dishonest", category: "emotion", difficulty: 3, hint: "Lacking honesty" },
	{ value: "Disjointed", category: "emotion", difficulty: 3, hint: "Disconnected and disjointed" },
	{ value: "Disoriented", category: "emotion", difficulty: 3, hint: "Confused and lost" },
	{ value: "Dispossessed", category: "emotion", difficulty: 3, hint: "Deprived of possessions" },
	{ value: "Disavowed", category: "emotion", difficulty: 3, hint: "Denied and rejected" },
];

export default items;
