import type { ICategoryWord } from "../api/items/words.get";

const items: ICategoryWord[] = [
	{ value: "Dog", category: "animal", difficulty: 1, hint: "Common household pet" },
	{ value: "Cat", category: "animal", difficulty: 1, hint: "Independent companion" },
	{ value: "Bird", category: "animal", difficulty: 1, hint: "Feathered creature" },
	{ value: "Fish", category: "animal", difficulty: 1, hint: "Swims in water" },
	{ value: "Mouse", category: "animal", difficulty: 1, hint: "Small rodent" },
	{ value: "Pig", category: "animal", difficulty: 1, hint: "Oinks and rolls in mud" },
	{ value: "Cow", category: "animal", difficulty: 1, hint: "Produces milk" },
	{ value: "Sheep", category: "animal", difficulty: 1, hint: "Grazes on grass" },
	{ value: "Goat", category: "animal", difficulty: 1, hint: "Often found on mountains" },
	{ value: "Chicken", category: "animal", difficulty: 1, hint: "Lays eggs" },
	{ value: "Duck", category: "animal", difficulty: 1, hint: "Quacks and swims" },
	{ value: "Turkey", category: "animal", difficulty: 1, hint: "Thanksgiving dinner" },
	{ value: "Rabbit", category: "animal", difficulty: 1, hint: "Hops and has long ears" },
	{ value: "Horse", category: "animal", difficulty: 1, hint: "Rides and races" },
	{ value: "Bear", category: "animal", difficulty: 1, hint: "Big and furry" },
	{ value: "Wolf", category: "animal", difficulty: 1, hint: "Howls at the moon" },
	{ value: "Fox", category: "animal", difficulty: 1, hint: "Sly and cunning" },
	{ value: "Elephant", category: "animal", difficulty: 1, hint: "Large trunked mammal" },
	{ value: "Tiger", category: "animal", difficulty: 1, hint: "Striped predator" },
	{ value: "Lion", category: "animal", difficulty: 1, hint: "King of the jungle" },
	{ value: "Giraffe", category: "animal", difficulty: 1, hint: "Tall with a long neck" },
	{ value: "Zebra", category: "animal", difficulty: 1, hint: "Black and white stripes" },
	{ value: "Rhino", category: "animal", difficulty: 1, hint: "Has a horn on its nose" },
	{ value: "Kangaroo", category: "animal", difficulty: 1, hint: "Carries a joey in its pouch" },
	{ value: "Koala", category: "animal", difficulty: 1, hint: "Sleeps in eucalyptus trees" },
	{ value: "Panda", category: "animal", difficulty: 1, hint: "Black and white bear" },
	{ value: "Monkey", category: "animal", difficulty: 1, hint: "Swings from trees" },
	{ value: "Sloth", category: "animal", difficulty: 1, hint: "Moves very slowly" },
	{ value: "Penguin", category: "animal", difficulty: 1, hint: "Waddles and swims" },
	{ value: "Seal", category: "animal", difficulty: 1, hint: "Plays in the ocean" },
	{ value: "Walrus", category: "animal", difficulty: 1, hint: "Tusks and blubbery" },
	{ value: "Ostrich", category: "animal", difficulty: 1, hint: "Tall and fast runner" },
	{ value: "Polar Bear", category: "animal", difficulty: 1, hint: "White fur and lives in the Arctic" },
	{ value: "Coyote", category: "animal", difficulty: 1, hint: "Howls at the moon" },
	{ value: "Skunk", category: "animal", difficulty: 1, hint: "Sprays a foul odor" },
	{ value: "Raccoon", category: "animal", difficulty: 1, hint: "Masked bandit" },
	{ value: "Beaver", category: "animal", difficulty: 1, hint: "Builds dams" },
	{ value: "Otter", category: "animal", difficulty: 1, hint: "Plays in rivers" },
	{ value: "Squirrel", category: "animal", difficulty: 1, hint: "Collects nuts" },
	{ value: "Chipmunk", category: "animal", difficulty: 1, hint: "Striped and small" },
	{ value: "Meerkat", category: "animal", difficulty: 1, hint: "Lives in groups called mobs" },
	{ value: "Ferret", category: "animal", difficulty: 1, hint: "Long and slinky" },
	{ value: "Armadillo", category: "animal", difficulty: 1, hint: "Has a shell" },
	{ value: "Fossa", category: "animal", difficulty: 1, hint: "Related to mongoose" },
	{ value: "Okapi", category: "animal", difficulty: 1, hint: "Looks like a mix of zebra and giraffe" },
	{ value: "Komodo Dragon", category: "animal", difficulty: 1, hint: "Large lizard" },
	{ value: "Blue Whale", category: "animal", difficulty: 1, hint: "Largest animal on Earth" },
	{ value: "Great White Shark", category: "animal", difficulty: 1, hint: "Apex predator of the sea" },
	{ value: "Humpback Whale", category: "animal", difficulty: 1, hint: "Known for its songs" },
	{ value: "Beluga Whale", category: "animal", difficulty: 1, hint: "White and lives in cold waters" },
	{ value: "Manta Ray", category: "animal", difficulty: 1, hint: "Giant and graceful in the ocean" },
	{ value: "Stingray", category: "animal", difficulty: 1, hint: "Flat and with a stinger" },
	{ value: "Alligator", category: "animal", difficulty: 1, hint: "Has a long snout and sharp teeth" },
	{ value: "Crocodile", category: "animal", difficulty: 1, hint: "Similar to an alligator" },
	{ value: "Anaconda", category: "animal", difficulty: 1, hint: "Large snake that squeezes its prey" },
	{ value: "Python", category: "animal", difficulty: 1, hint: "Constricting snake" },
	{ value: "Gila Monster", category: "animal", difficulty: 1, hint: "Venomous lizard" },
	{ value: "Rattlesnake", category: "animal", difficulty: 1, hint: "Has a rattle on its tail" },
	{ value: "Coral Snake", category: "animal", difficulty: 1, hint: "Colorful but venomous" },
	{ value: "Cottonmouth", category: "animal", difficulty: 1, hint: "Venomous snake found near water" },
	{ value: "Boa Constrictor", category: "animal", difficulty: 1, hint: "Squeezes its prey" },
	{ value: "Gorilla", category: "animal", difficulty: 2, hint: "Large primate" },
	{ value: "Chimpanzee", category: "animal", difficulty: 2, hint: "Close relative of humans" },
	{ value: "Orangutan", category: "animal", difficulty: 2, hint: "Reddish ape from Asia" },
	{ value: "Antelope", category: "animal", difficulty: 2, hint: "Hoofed mammal often found in herds" },
	{ value: "Buffalo", category: "animal", difficulty: 2, hint: "Large bovine with curved horns" },
	{ value: "Camel", category: "animal", difficulty: 2, hint: "Known for its humps" },
	{ value: "Llama", category: "animal", difficulty: 2, hint: "Domesticated South American animal" },
	{ value: "Alpaca", category: "animal", difficulty: 2, hint: "Similar to a llama" },
	{ value: "Emu", category: "animal", difficulty: 2, hint: "Large flightless bird from Australia" },
	{ value: "Hippopotamus", category: "animal", difficulty: 2, hint: "Large mammal that loves water" },
	{ value: "Wolverine", category: "animal", difficulty: 2, hint: "Small but fierce predator" },
	{ value: "Lynx", category: "animal", difficulty: 2, hint: "Wild cat with tufted ears" },
	{ value: "Bobcat", category: "animal", difficulty: 2, hint: "North American wild cat" },
	{ value: "Hyena", category: "animal", difficulty: 2, hint: "Laughing scavenger" },
	{ value: "Dingo", category: "animal", difficulty: 2, hint: "Wild dog from Australia" },
	{ value: "Fennec Fox", category: "animal", difficulty: 2, hint: "Small fox with large ears" },
	{ value: "Aardwolf", category: "animal", difficulty: 2, hint: "Eats termites" },
	{ value: "Dugong", category: "animal", difficulty: 2, hint: "Marine mammal related to manatees" },
	{ value: "Giant Anteater", category: "animal", difficulty: 2, hint: "Eats ants with its long tongue" },
	{ value: "Tasmanian Devil", category: "animal", difficulty: 2, hint: "Spins like a tornado" },
	{ value: "Jaguar", category: "animal", difficulty: 2, hint: "Spotted big cat of the Americas" },
	{ value: "Leopard", category: "animal", difficulty: 2, hint: "Spotted big cat" },
	{ value: "Panther", category: "animal", difficulty: 2, hint: "Black variant of a big cat" },
	{ value: "Cheetah", category: "animal", difficulty: 2, hint: "Fastest land animal" },
	{ value: "Tapir", category: "animal", difficulty: 2, hint: "Trunked mammal" },
	{ value: "Gazelle", category: "animal", difficulty: 2, hint: "Swift antelope" },
	{ value: "Impala", category: "animal", difficulty: 2, hint: "Medium-sized antelope" },
	{ value: "Moose", category: "animal", difficulty: 2, hint: "Large deer with antlers" },
	{ value: "Caribou", category: "animal", difficulty: 2, hint: "North American reindeer" },
	{ value: "Bison", category: "animal", difficulty: 2, hint: "Massive hoofed mammal of the plains" },
	{ value: "Giant Panda", category: "animal", difficulty: 2, hint: "Black and white bear" },
	{ value: "Red Panda", category: "animal", difficulty: 2, hint: "Cute and reddish" },
	{ value: "Tamarin", category: "animal", difficulty: 2, hint: "Small monkey" },
	{ value: "Capuchin Monkey", category: "animal", difficulty: 2, hint: "Often seen in movies" },
	{ value: "Baboon", category: "animal", difficulty: 2, hint: "Large monkey with a colorful rear" },
	{ value: "Mandrill", category: "animal", difficulty: 2, hint: "Colorful monkey" },
	{ value: "Proboscis Monkey", category: "animal", difficulty: 2, hint: "Has a big nose" },
	{ value: "Gibbon", category: "animal", difficulty: 2, hint: "Long-armed ape" },
	{ value: "Spider Monkey", category: "animal", difficulty: 2, hint: "Prehensile-tailed primate" },
	{ value: "Marmoset", category: "animal", difficulty: 2, hint: "Tiny monkey" },
	{ value: "Tarsier", category: "animal", difficulty: 2, hint: "Has huge eyes" },
	{ value: "Bat", category: "animal", difficulty: 2, hint: "Flies at night" },
	{ value: "Porcupine", category: "animal", difficulty: 3, hint: "Covered in sharp quills" },
	{ value: "Hummingbird", category: "animal", difficulty: 3, hint: "Flies backward and hovers" },
	{ value: "Woodpecker", category: "animal", difficulty: 3, hint: "Taps on trees with its beak" },
	{ value: "Pigeon", category: "animal", difficulty: 3, hint: "Common city bird" },
	{ value: "Toucan", category: "animal", difficulty: 3, hint: "Large-billed tropical bird" },
	{ value: "Roadrunner", category: "animal", difficulty: 3, hint: "Fast-running bird of the desert" },
	{ value: "Starling", category: "animal", difficulty: 3, hint: "Known for its murmurations" },
	{ value: "Rat", category: "animal", difficulty: 3, hint: "Carries diseases" },
	{ value: "Hedgehog", category: "animal", difficulty: 3, hint: "Covered in spikes" },
	{ value: "Frog", category: "animal", difficulty: 3, hint: "Amphibian that hops" },
	{ value: "Toad", category: "animal", difficulty: 3, hint: "Rough-skinned amphibian" },
	{ value: "Newt", category: "animal", difficulty: 3, hint: "Has bright colors" },
	{ value: "Salamander", category: "animal", difficulty: 3, hint: "Amphibian with a long body" },
	{ value: "Axolotl", category: "animal", difficulty: 3, hint: "Mexican amphibian with regenerative abilities" },
	{ value: "Caecilian", category: "animal", difficulty: 3, hint: "Legless amphibian" },
	{ value: "Mongoose", category: "animal", difficulty: 3, hint: "Fights snakes" },
	{ value: "Pangolin", category: "animal", difficulty: 3, hint: "Covered in scales" },
	{ value: "Pika", category: "animal", difficulty: 3, hint: "Small mountain-dwelling mammal" },
	{ value: "Hyrax", category: "animal", difficulty: 3, hint: "Small, thickset herbivore" },
	{ value: "Dormouse", category: "animal", difficulty: 3, hint: "Sleepy rodent" },
	{ value: "Vole", category: "animal", difficulty: 3, hint: "Small rodent often found near water" },
	{ value: "Hamster", category: "animal", difficulty: 3, hint: "Common small pet" },
	{ value: "Gerbil", category: "animal", difficulty: 3, hint: "Long-tailed desert rodent" },
	{ value: "Guinea Pig", category: "animal", difficulty: 3, hint: "Domesticated rodent often used in experiments" },
	{ value: "Chinchilla", category: "animal", difficulty: 3, hint: "Soft-furred rodent" },
	{ value: "Degu", category: "animal", difficulty: 3, hint: "Small rodent from South America" },
	{ value: "Jerboa", category: "animal", difficulty: 3, hint: "Long-legged hopping rodent" },
	{ value: "Kangaroo Rat", category: "animal", difficulty: 3, hint: "Desert-dwelling rodent" },
	{ value: "Muskrat", category: "animal", difficulty: 3, hint: "Semi-aquatic rodent" },
	{ value: "Capybara", category: "animal", difficulty: 3, hint: "Largest rodent in the world" },
	{ value: "Nutria", category: "animal", difficulty: 3, hint: "Also known as a coypu" },
	{ value: "Coypu", category: "animal", difficulty: 3, hint: "Semi-aquatic rodent" },
	{ value: "Desman", category: "animal", difficulty: 3, hint: "Aquatic insectivore" },
	{ value: "Shrew", category: "animal", difficulty: 3, hint: "Small mammal with a pointed snout" },
	{ value: "Mole", category: "animal", difficulty: 3, hint: "Digs underground" },
	{ value: "Platypus", category: "animal", difficulty: 3, hint: "Lays eggs and has a bill like a duck" },
	{ value: "Echidna", category: "animal", difficulty: 3, hint: "Spiky monotreme" },
	{ value: "Aardvark", category: "animal", difficulty: 3, hint: "Eats ants and termites" },
	{ value: "Anteater", category: "animal", difficulty: 3, hint: "Eats ants and termites" },
	{ value: "Manatee", category: "animal", difficulty: 3, hint: "Also known as a sea cow" },
	{ value: "Elephant Seal", category: "animal", difficulty: 3, hint: "Large seal with a trunk-like nose" },
	{ value: "Giant Otter", category: "animal", difficulty: 3, hint: "Large aquatic mammal with webbed feet" },
	{ value: "Albatross", category: "animal", difficulty: 3, hint: "Large seabird with long wings" },
	{ value: "Sparrow", category: "animal", difficulty: 3, hint: "Small bird often found in cities" },
	{ value: "Eagle", category: "animal", difficulty: 3, hint: "Symbol of freedom" },
	{ value: "Peregrine Falcon", category: "animal", difficulty: 3, hint: "Fastest animal in the sky" },
	{ value: "Condor", category: "animal", difficulty: 3, hint: "Large bird with a bald head" },
	{ value: "Vulture", category: "animal", difficulty: 3, hint: "Scavenges for food" },
	{ value: "Owl", category: "animal", difficulty: 3, hint: "Nocturnal bird of prey" },
	{ value: "Raven", category: "animal", difficulty: 3, hint: "Associated with mystery and magic" },
	{ value: "Crow", category: "animal", difficulty: 3, hint: "Often seen in groups" },
	{ value: "Swan", category: "animal", difficulty: 3, hint: "Graceful waterfowl" },
	{ value: "Crane", category: "animal", difficulty: 3, hint: "Long-legged bird" },
	{ value: "Pelican", category: "animal", difficulty: 3, hint: "Has a large pouch under its beak" },
	{ value: "Stork", category: "animal", difficulty: 3, hint: "Brings babies" },
	{ value: "Flamingo", category: "animal", difficulty: 3, hint: "Pink wading bird" },
	{ value: "Puffin", category: "animal", difficulty: 3, hint: "Colorful seabird with a distinctive beak" },
];

export default items;
