import type { ICategoryWord } from "../api/items/words.get";

const items: ICategoryWord[] = [
	{ value: "Apple", category: "food", difficulty: 1, hint: "Red fruit" },
	{ value: "Banana", category: "food", difficulty: 1, hint: "Yellow fruit" },
	{ value: "Orange", category: "food", difficulty: 1, hint: "Citrus fruit" },
	{ value: "Grapes", category: "food", difficulty: 1, hint: "Small round fruit" },
	{ value: "Strawberry", category: "food", difficulty: 1, hint: "Red berry" },
	{ value: "Watermelon", category: "food", difficulty: 1, hint: "Large green fruit" },
	{ value: "Pineapple", category: "food", difficulty: 1, hint: "Tropical fruit" },
	{ value: "Mango", category: "food", difficulty: 1, hint: "Tropical fruit" },
	{ value: "Peach", category: "food", difficulty: 1, hint: "Fuzzy fruit" },
	{ value: "Pear", category: "food", difficulty: 1, hint: "Fruit with a core" },
	{ value: "Cherry", category: "food", difficulty: 1, hint: "Small red fruit" },
	{ value: "Plum", category: "food", difficulty: 1, hint: "Purple fruit" },
	{ value: "Kiwi", category: "food", difficulty: 1, hint: "Brown fuzzy fruit" },
	{ value: "Apricot", category: "food", difficulty: 1, hint: "Yellow fruit" },
	{ value: "Coconut", category: "food", difficulty: 1, hint: "Tropical fruit" },
	{ value: "Lemon", category: "food", difficulty: 1, hint: "Yellow citrus fruit" },
	{ value: "Lime", category: "food", difficulty: 1, hint: "Green citrus fruit" },
	{ value: "Blueberry", category: "food", difficulty: 1, hint: "Small round fruit" },
	{ value: "Raspberry", category: "food", difficulty: 1, hint: "Red berry" },
	{ value: "Blackberry", category: "food", difficulty: 1, hint: "Dark berry" },
	{ value: "Cantaloupe", category: "food", difficulty: 1, hint: "Orange melon" },
	{ value: "Honeydew", category: "food", difficulty: 1, hint: "Green melon" },
	{ value: "Pomegranate", category: "food", difficulty: 1, hint: "Red fruit with seeds" },
	{ value: "Cranberry", category: "food", difficulty: 1, hint: "Red berry" },
	{ value: "Fig", category: "food", difficulty: 1, hint: "Purple fruit" },
	{ value: "Papaya", category: "food", difficulty: 1, hint: "Tropical fruit" },
	{ value: "Passionfruit", category: "food", difficulty: 1, hint: "Tropical fruit" },
	{ value: "Guava", category: "food", difficulty: 1, hint: "Tropical fruit" },
	{ value: "Lychee", category: "food", difficulty: 1, hint: "Small tropical fruit" },
	{ value: "Starfruit", category: "food", difficulty: 1, hint: "Yellow fruit" },
	{ value: "Persimmon", category: "food", difficulty: 1, hint: "Orange fruit" },
	{ value: "Dragonfruit", category: "food", difficulty: 1, hint: "Tropical fruit" },
	{ value: "Avocado", category: "food", difficulty: 1, hint: "Green fruit" },
	{ value: "Tomato", category: "food", difficulty: 1, hint: "Red vegetable" },
	{ value: "Cucumber", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Carrot", category: "food", difficulty: 1, hint: "Orange vegetable" },
	{ value: "Lettuce", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Spinach", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Kale", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Broccoli", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Cauliflower", category: "food", difficulty: 1, hint: "White vegetable" },
	{ value: "Celery", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Bell Pepper", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Onion", category: "food", difficulty: 1, hint: "White vegetable" },
	{ value: "Garlic", category: "food", difficulty: 1, hint: "White vegetable" },
	{ value: "Potato", category: "food", difficulty: 1, hint: "Starchy vegetable" },
	{ value: "Sweet Potato", category: "food", difficulty: 1, hint: "Orange vegetable" },
	{ value: "Corn", category: "food", difficulty: 1, hint: "Yellow vegetable" },
	{ value: "Peas", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Green Bean", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Asparagus", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Eggplant", category: "food", difficulty: 1, hint: "Purple vegetable" },
	{ value: "Mushroom", category: "food", difficulty: 1, hint: "Edible fungus" },
	{ value: "Radish", category: "food", difficulty: 1, hint: "Red vegetable" },
	{ value: "Beet", category: "food", difficulty: 1, hint: "Red vegetable" },
	{ value: "Turnip", category: "food", difficulty: 1, hint: "White vegetable" },
	{ value: "Rutabaga", category: "food", difficulty: 1, hint: "Yellow vegetable" },
	{ value: "Parsnip", category: "food", difficulty: 1, hint: "White vegetable" },
	{ value: "Artichoke", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Brussels Sprouts", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Cabbage", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Chili Pepper", category: "food", difficulty: 1, hint: "Spicy vegetable" },
	{ value: "Jalapeño", category: "food", difficulty: 1, hint: "Spicy vegetable" },
	{ value: "Serrano Pepper", category: "food", difficulty: 1, hint: "Spicy vegetable" },
	{ value: "Poblano Pepper", category: "food", difficulty: 1, hint: "Spicy vegetable" },
	{ value: "Habanero Pepper", category: "food", difficulty: 1, hint: "Spicy vegetable" },
	{ value: "Anaheim Pepper", category: "food", difficulty: 1, hint: "Spicy vegetable" },
	{ value: "Cayenne Pepper", category: "food", difficulty: 1, hint: "Spicy vegetable" },
	{ value: "Tabasco Pepper", category: "food", difficulty: 1, hint: "Spicy vegetable" },
	{ value: "Squash", category: "food", difficulty: 1, hint: "Yellow vegetable" },
	{ value: "Butternut Squash", category: "food", difficulty: 1, hint: "Orange vegetable" },
	{ value: "Acorn Squash", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Spaghetti Squash", category: "food", difficulty: 1, hint: "Yellow vegetable" },
	{ value: "Pattypan Squash", category: "food", difficulty: 1, hint: "Yellow vegetable" },
	{ value: "Yellow Squash", category: "food", difficulty: 1, hint: "Yellow vegetable" },
	{ value: "Zucchini", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Chayote", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Okra", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Arugula", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Endive", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Radicchio", category: "food", difficulty: 1, hint: "Red leafy green" },
	{ value: "Watercress", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Fennel", category: "food", difficulty: 1, hint: "White vegetable" },
	{ value: "Bok Choy", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Chard", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Collard Greens", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Mustard Greens", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Dandelion Greens", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Turnip Greens", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Kohlrabi", category: "food", difficulty: 1, hint: "Green vegetable" },
	{ value: "Sorrel", category: "food", difficulty: 1, hint: "Leafy green" },
	{ value: "Bread", category: "food", difficulty: 2, hint: "Bakery item" },
	{ value: "Rice", category: "food", difficulty: 2, hint: "Staple food" },
	{ value: "Pasta", category: "food", difficulty: 2, hint: "Italian dish" },
	{ value: "Noodles", category: "food", difficulty: 2, hint: "Asian food" },
	{ value: "Bagel", category: "food", difficulty: 2, hint: "Breakfast bread" },
	{ value: "Croissant", category: "food", difficulty: 2, hint: "French pastry" },
	{ value: "Muffin", category: "food", difficulty: 2, hint: "Breakfast item" },
	{ value: "Biscuit", category: "food", difficulty: 2, hint: "Flaky bread" },
	{ value: "Pancake", category: "food", difficulty: 2, hint: "Breakfast item" },
	{ value: "Waffle", category: "food", difficulty: 2, hint: "Breakfast item" },
	{ value: "French Toast", category: "food", difficulty: 2, hint: "Breakfast item" },
	{ value: "Crepe", category: "food", difficulty: 2, hint: "Thin pancake" },
	{ value: "Donut", category: "food", difficulty: 2, hint: "Sweet pastry" },
	{ value: "Pie", category: "food", difficulty: 2, hint: "Dessert" },
	{ value: "Cake", category: "food", difficulty: 2, hint: "Dessert" },
	{ value: "Cupcake", category: "food", difficulty: 2, hint: "Mini cake" },
	{ value: "Brownie", category: "food", difficulty: 2, hint: "Chocolate dessert" },
	{ value: "Cookie", category: "food", difficulty: 2, hint: "Sweet treat" },
	{ value: "Macaron", category: "food", difficulty: 2, hint: "French pastry" },
	{ value: "Meringue", category: "food", difficulty: 2, hint: "Light dessert" },
	{ value: "Cheesecake", category: "food", difficulty: 2, hint: "Creamy dessert" },
	{ value: "Cobbler", category: "food", difficulty: 2, hint: "Fruit dessert" },
	{ value: "Tart", category: "food", difficulty: 2, hint: "Fruit dessert" },
	{ value: "Creme Brulee", category: "food", difficulty: 2, hint: "Dessert with caramelized top" },
	{ value: "Pudding", category: "food", difficulty: 2, hint: "Creamy dessert" },
	{ value: "Gelato", category: "food", difficulty: 2, hint: "Italian ice cream" },
	{ value: "Ice Cream", category: "food", difficulty: 2, hint: "Frozen dessert" },
	{ value: "Sorbet", category: "food", difficulty: 2, hint: "Frozen dessert" },
	{ value: "Frozen Yogurt", category: "food", difficulty: 2, hint: "Frozen dessert" },
	{ value: "Sherbet", category: "food", difficulty: 2, hint: "Frozen dessert" },
	{ value: "Mousse", category: "food", difficulty: 2, hint: "Light dessert" },
	{ value: "Parfait", category: "food", difficulty: 2, hint: "Layered dessert" },
	{ value: "Trifle", category: "food", difficulty: 2, hint: "Layered dessert" },
	{ value: "Tiramisu", category: "food", difficulty: 2, hint: "Italian dessert" },
	{ value: "Baklava", category: "food", difficulty: 2, hint: "Middle Eastern dessert" },
	{ value: "Cannoli", category: "food", difficulty: 2, hint: "Italian dessert" },
	{ value: "Eclair", category: "food", difficulty: 2, hint: "French pastry" },
	{ value: "Macaroon", category: "food", difficulty: 2, hint: "Coconut dessert" },
	{ value: "Scone", category: "food", difficulty: 2, hint: "British pastry" },
	{ value: "Shortbread", category: "food", difficulty: 2, hint: "Buttery biscuit" },
	{ value: "Turnover", category: "food", difficulty: 2, hint: "Pastry" },
	{ value: "Brioche", category: "food", difficulty: 2, hint: "French bread" },
	{ value: "Danish", category: "food", difficulty: 2, hint: "Pastry" },
	{ value: "Churro", category: "food", difficulty: 2, hint: "Spanish dessert" },
	{ value: "Challah", category: "food", difficulty: 2, hint: "Jewish bread" },
	{ value: "Focaccia", category: "food", difficulty: 2, hint: "Italian bread" },
	{ value: "Naan", category: "food", difficulty: 2, hint: "Indian bread" },
	{ value: "Pita", category: "food", difficulty: 2, hint: "Middle Eastern bread" },
	{ value: "Baguette", category: "food", difficulty: 2, hint: "French bread" },
	{ value: "Ciabatta", category: "food", difficulty: 2, hint: "Italian bread" },
	{ value: "Sourdough", category: "food", difficulty: 2, hint: "Fermented bread" },
	{ value: "English Muffin", category: "food", difficulty: 2, hint: "Breakfast bread" },
	{ value: "Garlic Bread", category: "food", difficulty: 2, hint: "Flavored bread" },
	{ value: "Flatbread", category: "food", difficulty: 2, hint: "Thin bread" },
	{ value: "Tortilla", category: "food", difficulty: 2, hint: "Mexican bread" },
	{ value: "Roti", category: "food", difficulty: 2, hint: "Indian bread" },
	{ value: "Chapati", category: "food", difficulty: 2, hint: "Indian bread" },
	{ value: "Cracker", category: "food", difficulty: 2, hint: "Snack" },
	{ value: "Chip", category: "food", difficulty: 2, hint: "Snack" },
	{ value: "Popcorn", category: "food", difficulty: 2, hint: "Snack" },
	{ value: "Pretzel", category: "food", difficulty: 2, hint: "Salty snack" },
	{ value: "Cheese", category: "food", difficulty: 2, hint: "Dairy product" },
	{ value: "Butter", category: "food", difficulty: 2, hint: "Dairy product" },
	{ value: "Yogurt", category: "food", difficulty: 2, hint: "Dairy product" },
	{ value: "Sour Cream", category: "food", difficulty: 2, hint: "Dairy product" },
	{ value: "Cream Cheese", category: "food", difficulty: 2, hint: "Dairy product" },
	{ value: "Whipped Cream", category: "food", difficulty: 2, hint: "Dessert topping" },
	{ value: "Margarine", category: "food", difficulty: 2, hint: "Butter substitute" },
	{ value: "Mayonnaise", category: "food", difficulty: 2, hint: "Condiment" },
	{ value: "Ketchup", category: "food", difficulty: 2, hint: "Red condiment" },
	{ value: "Mustard", category: "food", difficulty: 2, hint: "Yellow condiment" },
	{ value: "Relish", category: "food", difficulty: 2, hint: "Condiment" },
	{ value: "Salsa", category: "food", difficulty: 2, hint: "Mexican condiment" },
	{ value: "Guacamole", category: "food", difficulty: 2, hint: "Mexican condiment" },
	{ value: "Hummus", category: "food", difficulty: 2, hint: "Middle Eastern dip" },
	{ value: "Tahini", category: "food", difficulty: 2, hint: "Middle Eastern condiment" },
	{ value: "Peanut Butter", category: "food", difficulty: 2, hint: "Spread" },
	{ value: "Nutella", category: "food", difficulty: 2, hint: "Chocolate spread" },
	{ value: "Jelly", category: "food", difficulty: 2, hint: "Sweet spread" },
	{ value: "Maple Syrup", category: "food", difficulty: 2, hint: "Sweet syrup" },
	{ value: "Honey", category: "food", difficulty: 2, hint: "Sweet syrup" },
	{ value: "Molasses", category: "food", difficulty: 2, hint: "Sweet syrup" },
	{ value: "Jam", category: "food", difficulty: 2, hint: "Sweet spread" },
	{ value: "Preserves", category: "food", difficulty: 2, hint: "Sweet spread" },
	{ value: "Chocolate Spread", category: "food", difficulty: 2, hint: "Sweet spread" },
	{ value: "Cereal", category: "food", difficulty: 3, hint: "Breakfast food" },
	{ value: "Granola", category: "food", difficulty: 3, hint: "Breakfast food" },
	{ value: "Oatmeal", category: "food", difficulty: 3, hint: "Breakfast food" },
	{ value: "Porridge", category: "food", difficulty: 3, hint: "Breakfast food" },
	{ value: "Grits", category: "food", difficulty: 3, hint: "Southern dish" },
	{ value: "Quinoa", category: "food", difficulty: 3, hint: "Healthy grain" },
	{ value: "Bulgur", category: "food", difficulty: 3, hint: "Whole grain" },
	{ value: "Farro", category: "food", difficulty: 3, hint: "Ancient grain" },
	{ value: "Barley", category: "food", difficulty: 3, hint: "Whole grain" },
	{ value: "Polenta", category: "food", difficulty: 3, hint: "Italian dish" },
	{ value: "Couscous", category: "food", difficulty: 3, hint: "North African dish" },
	{ value: "Risotto", category: "food", difficulty: 3, hint: "Italian dish" },
	{ value: "Paella", category: "food", difficulty: 3, hint: "Spanish dish" },
	{ value: "Sushi", category: "food", difficulty: 3, hint: "Japanese dish" },
	{ value: "Tempura", category: "food", difficulty: 3, hint: "Japanese dish" },
	{ value: "California Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Spicy Tuna Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Philadelphia Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Rainbow Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Dragon Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Shrimp Tempura Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Spider Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Cucumber Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Avocado Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Tofu Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Salmon Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Tuna Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Eel Roll", category: "food", difficulty: 3, hint: "Sushi roll" },
	{ value: "Nigiri", category: "food", difficulty: 3, hint: "Japanese dish" },
	{ value: "Sashimi", category: "food", difficulty: 3, hint: "Japanese dish" },
	{ value: "Maki", category: "food", difficulty: 3, hint: "Japanese dish" },
	{ value: "Uramaki", category: "food", difficulty: 3, hint: "Japanese dish" },
	{ value: "Tamago", category: "food", difficulty: 3, hint: "Japanese dish" },
	{ value: "Wasabi", category: "food", difficulty: 3, hint: "Japanese condiment" },
	{ value: "Ginger", category: "food", difficulty: 3, hint: "Japanese condiment" },
	{ value: "Soy Sauce", category: "food", difficulty: 3, hint: "Japanese condiment" },
	{ value: "Seaweed", category: "food", difficulty: 3, hint: "Japanese ingredient" },
	{ value: "Green Tea", category: "food", difficulty: 3, hint: "Japanese drink" },
	{ value: "Oolong Tea", category: "food", difficulty: 3, hint: "Chinese tea" },
	{ value: "Chai", category: "food", difficulty: 3, hint: "Indian tea" },
	{ value: "Chamomile Tea", category: "food", difficulty: 3, hint: "Herbal tea" },
	{ value: "Peppermint Tea", category: "food", difficulty: 3, hint: "Herbal tea" },
	{ value: "Black Tea", category: "food", difficulty: 3, hint: "Strong tea" },
	{ value: "Earl Grey Tea", category: "food", difficulty: 3, hint: "Flavored tea" },
	{ value: "Bubble Tea", category: "food", difficulty: 3, hint: "Asian drink" },
	{ value: "Matcha", category: "food", difficulty: 3, hint: "Japanese green tea" },
	{ value: "Smoothie", category: "food", difficulty: 3, hint: "Blended drink" },
	{ value: "Milkshake", category: "food", difficulty: 3, hint: "Frozen drink" },
	{ value: "Juice", category: "food", difficulty: 3, hint: "Fruit drink" },
	{ value: "Soda", category: "food", difficulty: 3, hint: "Carbonated drink" },
	{ value: "Coffee", category: "food", difficulty: 3, hint: "Caffeinated drink" },
	{ value: "Espresso", category: "food", difficulty: 3, hint: "Strong coffee" },
	{ value: "Latte", category: "food", difficulty: 3, hint: "Coffee drink" },
	{ value: "Cappuccino", category: "food", difficulty: 3, hint: "Coffee drink" },
	{ value: "Macchiato", category: "food", difficulty: 3, hint: "Coffee drink" },
	{ value: "Americano", category: "food", difficulty: 3, hint: "Coffee drink" },
	{ value: "Mocha", category: "food", difficulty: 3, hint: "Coffee drink" },
	{ value: "Irish Coffee", category: "food", difficulty: 3, hint: "Coffee drink" },
	{ value: "Cortado", category: "food", difficulty: 3, hint: "Coffee drink" },
	{ value: "Red Wine", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "White Wine", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Rosé Wine", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Champagne", category: "food", difficulty: 3, hint: "Sparkling wine" },
	{ value: "Prosecco", category: "food", difficulty: 3, hint: "Sparkling wine" },
	{ value: "Sake", category: "food", difficulty: 3, hint: "Japanese drink" },
	{ value: "Soju", category: "food", difficulty: 3, hint: "Korean drink" },
	{ value: "Tequila", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Vodka", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Rum", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Gin", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Whiskey", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Brandy", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Cognac", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Absinthe", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Liqueur", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Beer", category: "food", difficulty: 3, hint: "Alcoholic drink" },
	{ value: "Ale", category: "food", difficulty: 3, hint: "Type of beer" },
];

export default items;
