import type { ICategoryWord } from "../api/items/words.get";

const items: ICategoryWord[] = [
	{ value: "Walking", category: "activity", difficulty: 1, hint: "Moving on foot" },
	{ value: "Running", category: "activity", difficulty: 1, hint: "Jogging quickly" },
	{ value: "Jumping", category: "activity", difficulty: 1, hint: "Springing into the air" },
	{ value: "Cycling", category: "activity", difficulty: 1, hint: "Riding a bike" },
	{ value: "Swimming", category: "activity", difficulty: 1, hint: "Moving in water" },
	{ value: "Reading", category: "activity", difficulty: 1, hint: "Perusing written text" },
	{ value: "Cooking", category: "activity", difficulty: 1, hint: "Preparing food" },
	{ value: "Dancing", category: "activity", difficulty: 1, hint: "Moving rhythmically" },
	{ value: "Painting", category: "activity", difficulty: 1, hint: "Creating art with colors" },
	{ value: "Jogging", category: "activity", difficulty: 1, hint: "Running slowly" },
	{ value: "Gardening", category: "activity", difficulty: 1, hint: "Cultivating plants" },
	{ value: "Singing", category: "activity", difficulty: 1, hint: "Using voice melodically" },
	{ value: "Bowling", category: "activity", difficulty: 1, hint: "Rolling a ball at pins" },
	{ value: "Fishing", category: "activity", difficulty: 1, hint: "Catching aquatic animals" },
	{ value: "Baking", category: "activity", difficulty: 1, hint: "Cooking in an oven" },
	{ value: "Shopping", category: "activity", difficulty: 1, hint: "Buying goods" },
	{ value: "Hiking", category: "activity", difficulty: 1, hint: "Walking in nature" },
	{ value: "Playing", category: "activity", difficulty: 1, hint: "Engaging in recreation" },
	{ value: "Driving", category: "activity", difficulty: 1, hint: "Operating a vehicle" },
	{ value: "Cleaning", category: "activity", difficulty: 1, hint: "Removing dirt" },
	{ value: "Writing", category: "activity", difficulty: 1, hint: "Putting thoughts into words" },
	{ value: "Drawing", category: "activity", difficulty: 1, hint: "Creating pictures" },
	{ value: "Eating", category: "activity", difficulty: 1, hint: "Consuming food" },
	{ value: "Sleeping", category: "activity", difficulty: 1, hint: "Resting in bed" },
	{ value: "Watching TV", category: "activity", difficulty: 1, hint: "Viewing television" },
	{ value: "Listening to music", category: "activity", difficulty: 1, hint: "Hearing musical sounds" },
	{ value: "Texting", category: "activity", difficulty: 1, hint: "Sending written messages" },
	{ value: "Talking", category: "activity", difficulty: 1, hint: "Conversing verbally" },
	{ value: "Laughing", category: "activity", difficulty: 1, hint: "Expressing amusement" },
	{ value: "Smiling", category: "activity", difficulty: 1, hint: "Expressing happiness" },
	{ value: "Golfing", category: "activity", difficulty: 1, hint: "Playing golf" },
	{ value: "Exercising", category: "activity", difficulty: 1, hint: "Physical activity" },
	{ value: "Meditating", category: "activity", difficulty: 1, hint: "Contemplative practice" },
	{ value: "Travelling", category: "activity", difficulty: 1, hint: "Journeying to places" },
	{ value: "Snorkeling", category: "activity", difficulty: 1, hint: "Swimming with snorkel" },
	{ value: "Picnicking", category: "activity", difficulty: 1, hint: "Eating outdoors" },
	{ value: "Sunbathing", category: "activity", difficulty: 1, hint: "Basking in sunlight" },
	{ value: "Hula Hooping", category: "activity", difficulty: 1, hint: "Using a hoop for fun" },
	{ value: "Photography", category: "activity", difficulty: 1, hint: "Taking pictures" },
	{ value: "Surfing", category: "activity", difficulty: 1, hint: "Riding waves" },
	{ value: "Ice Skating", category: "activity", difficulty: 1, hint: "Skating on ice" },
	{ value: "Pilates", category: "activity", difficulty: 1, hint: "Exercise system" },
	{ value: "Scuba Diving", category: "activity", difficulty: 1, hint: "Underwater diving" },
	{ value: "Chess", category: "activity", difficulty: 1, hint: "Strategic board game" },
	{ value: "Pottery", category: "activity", difficulty: 1, hint: "Creating ceramic objects" },
	{ value: "Yoga", category: "activity", difficulty: 1, hint: "Physical and mental discipline" },
	{ value: "Karaoke", category: "activity", difficulty: 1, hint: "Singing to music" },
	{ value: "Rock Climbing", category: "activity", difficulty: 1, hint: "Scaling rocks" },
	{ value: "Paddleboarding", category: "activity", difficulty: 1, hint: "Stand-up surfing" },
	{ value: "Camping", category: "activity", difficulty: 1, hint: "Outdoor sleeping" },
	{ value: "Zip Lining", category: "activity", difficulty: 1, hint: "Riding on a zip line" },
	{ value: "Horseback Riding", category: "activity", difficulty: 1, hint: "Riding on horse" },
	{ value: "Skydiving", category: "activity", difficulty: 1, hint: "Jumping from plane" },
	{ value: "Canoeing", category: "activity", difficulty: 1, hint: "Paddling in canoe" },
	{ value: "Skiing", category: "activity", difficulty: 1, hint: "Gliding on snow" },
	{ value: "Snowboarding", category: "activity", difficulty: 1, hint: "Riding snowboard" },
	{ value: "Windsurfing", category: "activity", difficulty: 1, hint: "Surfing with sail" },
	{ value: "Sailing", category: "activity", difficulty: 1, hint: "Navigating on water" },
	{ value: "Rollerblading", category: "activity", difficulty: 1, hint: "Skating with inline skates" },
	{ value: "Boxing", category: "activity", difficulty: 1, hint: "Combat sport" },
	{ value: "Kite Flying", category: "activity", difficulty: 1, hint: "Flying a kite" },
	{ value: "Jiu Jitsu", category: "activity", difficulty: 1, hint: "Martial art" },
	{ value: "Tai Chi", category: "activity", difficulty: 1, hint: "Chinese martial art" },
	{ value: "Frisbee", category: "activity", difficulty: 1, hint: "Flying disc game" },
	{ value: "Billiards", category: "activity", difficulty: 1, hint: "Pool game" },
	{ value: "Table Tennis", category: "activity", difficulty: 1, hint: "Ping pong" },
	{ value: "Rope Skipping", category: "activity", difficulty: 1, hint: "Jumping with rope" },
	{ value: "Badminton", category: "activity", difficulty: 1, hint: "Racket sport" },
	{ value: "Volleyball", category: "activity", difficulty: 1, hint: "Team sport" },
	{ value: "Basketball", category: "activity", difficulty: 1, hint: "Team sport with ball" },
	{ value: "Soccer", category: "activity", difficulty: 1, hint: "Football sport" },
	{ value: "Tennis", category: "activity", difficulty: 1, hint: "Racket sport" },
	{ value: "Baseball", category: "activity", difficulty: 1, hint: "Bat and ball sport" },
	{ value: "Football", category: "activity", difficulty: 1, hint: "American football" },
	{ value: "Rugby", category: "activity", difficulty: 1, hint: "Contact team sport" },
	{ value: "Cricket", category: "activity", difficulty: 1, hint: "Bat and ball sport" },
	{ value: "Ice Hockey", category: "activity", difficulty: 1, hint: "Hockey on ice" },
	{ value: "Gymnastics", category: "activity", difficulty: 1, hint: "Athletic discipline" },
	{ value: "Diving", category: "activity", difficulty: 1, hint: "Jumping into water" },
	{ value: "Rowing", category: "activity", difficulty: 1, hint: "Propelling boat with oars" },
	{ value: "Hockey", category: "activity", difficulty: 1, hint: "Ice or field sport" },
	{ value: "Handball", category: "activity", difficulty: 1, hint: "Team sport with ball" },
	{ value: "Weightlifting", category: "activity", difficulty: 1, hint: "Lifting heavy weights" },
	{ value: "Bodybuilding", category: "activity", difficulty: 1, hint: "Muscle development" },
	{ value: "Zumba", category: "activity", difficulty: 2, hint: "Dance fitness program" },
	{ value: "Ballet", category: "activity", difficulty: 2, hint: "Dance with classical music" },
	{ value: "Salsa Dancing", category: "activity", difficulty: 2, hint: "Latin dance style" },
	{ value: "Taekwondo", category: "activity", difficulty: 2, hint: "Korean martial art" },
	{ value: "Kickboxing", category: "activity", difficulty: 2, hint: "Martial art and sport" },
	{ value: "Breakdancing", category: "activity", difficulty: 2, hint: "Street dance style" },
	{ value: "Belly Dancing", category: "activity", difficulty: 2, hint: "Dance from Middle East" },
	{ value: "Bollywood Dancing", category: "activity", difficulty: 2, hint: "Indian film dance" },
	{ value: "Hip Hop Dancing", category: "activity", difficulty: 2, hint: "Street dance style" },
	{ value: "Parkour", category: "activity", difficulty: 2, hint: "Obstacle course training" },
	{ value: "Acrobatics", category: "activity", difficulty: 2, hint: "Aerial gymnastics" },
	{ value: "Circus Arts", category: "activity", difficulty: 2, hint: "Performance skills" },
	{ value: "Aerobics", category: "activity", difficulty: 2, hint: "Cardio exercise" },
	{ value: "Hula Dancing", category: "activity", difficulty: 2, hint: "Hawaiian dance" },
	{ value: "Capoeira", category: "activity", difficulty: 2, hint: "Brazilian martial art" },
	{ value: "Fire Dancing", category: "activity", difficulty: 2, hint: "Dancing with fire props" },
	{ value: "Body Combat", category: "activity", difficulty: 2, hint: "High-intensity workout" },
	{ value: "Piloxing", category: "activity", difficulty: 2, hint: "Pilates and boxing" },
	{ value: "Street Dance", category: "activity", difficulty: 2, hint: "Urban dance style" },
	{ value: "Latin Dance", category: "activity", difficulty: 2, hint: "Dance from Latin America" },
	{ value: "Ballroom Dance", category: "activity", difficulty: 2, hint: "Formal dance style" },
	{ value: "Line Dancing", category: "activity", difficulty: 2, hint: "Group dance in lines" },
	{ value: "Square Dancing", category: "activity", difficulty: 2, hint: "American folk dance" },
	{ value: "Tango", category: "activity", difficulty: 2, hint: "Passionate dance style" },
	{ value: "Swing Dancing", category: "activity", difficulty: 2, hint: "Jazz dance style" },
	{ value: "Samba", category: "activity", difficulty: 2, hint: "Brazilian dance style" },
	{ value: "Waltz", category: "activity", difficulty: 2, hint: "Elegant ballroom dance" },
	{ value: "Foxtrot", category: "activity", difficulty: 2, hint: "Smooth ballroom dance" },
	{ value: "Cha Cha", category: "activity", difficulty: 2, hint: "Latin dance style" },
	{ value: "Rumba", category: "activity", difficulty: 2, hint: "Latin dance style" },
	{ value: "Jive", category: "activity", difficulty: 2, hint: "Energetic dance style" },
	{ value: "Quickstep", category: "activity", difficulty: 2, hint: "Ballroom dance" },
	{ value: "Viennese Waltz", category: "activity", difficulty: 2, hint: "Elegant dance style" },
	{ value: "Merengue", category: "activity", difficulty: 2, hint: "Latin dance style" },
	{ value: "Synchronized Swimming", category: "activity", difficulty: 2, hint: "Swimming routine" },
	{ value: "Water Aerobics", category: "activity", difficulty: 2, hint: "Pool exercise" },
	{ value: "Water Zumba", category: "activity", difficulty: 2, hint: "Aquatic dance fitness" },
	{ value: "Water Polo", category: "activity", difficulty: 2, hint: "Pool ball sport" },
	{ value: "Water Ballet", category: "activity", difficulty: 2, hint: "Aquatic dance" },
	{ value: "Underwater Hockey", category: "activity", difficulty: 2, hint: "Pool game" },
	{ value: "Underwater Rugby", category: "activity", difficulty: 2, hint: "Pool sport" },
	{ value: "Paragliding", category: "activity", difficulty: 3, hint: "Gliding in air" },
	{ value: "Hang Gliding", category: "activity", difficulty: 3, hint: "Gliding with wings" },
	{ value: "Bungee Jumping", category: "activity", difficulty: 3, hint: "Jumping with elastic cord" },
	{ value: "Base Jumping", category: "activity", difficulty: 3, hint: "Jumping from fixed object" },
	{ value: "Cave Diving", category: "activity", difficulty: 3, hint: "Exploring underwater caves" },
	{ value: "Wingsuit Flying", category: "activity", difficulty: 3, hint: "Flying with wingsuit" },
	{ value: "Free Solo Climbing", category: "activity", difficulty: 3, hint: "Climbing without ropes" },
	{ value: "Ice Climbing", category: "activity", difficulty: 3, hint: "Scaling icy terrain" },
	{ value: "Mountaineering", category: "activity", difficulty: 3, hint: "Climbing mountains" },
	{ value: "Canyoning", category: "activity", difficulty: 3, hint: "Descending canyons" },
	{ value: "Free Diving", category: "activity", difficulty: 3, hint: "Diving without equipment" },
	{ value: "Deep-Sea Fishing", category: "activity", difficulty: 3, hint: "Fishing in deep waters" },
	{ value: "Kite Surfing", category: "activity", difficulty: 3, hint: "Surfing with kite" },
	{ value: "Big Wave Surfing", category: "activity", difficulty: 3, hint: "Surfing large waves" },
	{ value: "Wind Surfing", category: "activity", difficulty: 3, hint: "Surfing with sail" },
	{ value: "White Water Rafting", category: "activity", difficulty: 3, hint: "Rafting in rapids" },
	{ value: "Cave Exploration", category: "activity", difficulty: 3, hint: "Discovering caves" },
	{ value: "Safari", category: "activity", difficulty: 3, hint: "Wildlife expedition" },
	{ value: "Wildlife Photography", category: "activity", difficulty: 3, hint: "Photographing animals" },
	{ value: "Mountain Biking", category: "activity", difficulty: 3, hint: "Biking in mountains" },
	{ value: "BMX", category: "activity", difficulty: 3, hint: "Bicycle motocross" },
	{ value: "Motocross", category: "activity", difficulty: 3, hint: "Off-road motorcycle racing" },
	{ value: "Enduro", category: "activity", difficulty: 3, hint: "Long-distance motorcycle race" },
	{ value: "Triathlon", category: "activity", difficulty: 3, hint: "Multisport race" },
	{ value: "Decathlon", category: "activity", difficulty: 3, hint: "Athletic contest" },
	{ value: "Ultra Marathon", category: "activity", difficulty: 3, hint: "Long-distance race" },
	{ value: "Ironman", category: "activity", difficulty: 3, hint: "Endurance race" },
	{ value: "Biathlon", category: "activity", difficulty: 3, hint: "Combination sport" },
	{ value: "Obstacle Course Racing", category: "activity", difficulty: 3, hint: "Race with obstacles" },
	{ value: "Kendo", category: "activity", difficulty: 3, hint: "Japanese martial art" },
	{ value: "Jousting", category: "activity", difficulty: 3, hint: "Medieval sport" },
	{ value: "Sword Fighting", category: "activity", difficulty: 3, hint: "Combat with swords" },
	{ value: "Archery", category: "activity", difficulty: 3, hint: "Sport of shooting arrows" },
	{ value: "Shooting", category: "activity", difficulty: 3, hint: "Firing guns" },
	{ value: "Skeet Shooting", category: "activity", difficulty: 3, hint: "Clay target shooting" },
	{ value: "Trap Shooting", category: "activity", difficulty: 3, hint: "Shooting at moving targets" },
];

export default items;
