import type { ICategoryWord } from "../api/items/words.get";

const items: ICategoryWord[] = [
	{ value: "Box", category: "object", difficulty: 1, hint: "Container" },
	{ value: "Envelope", category: "object", difficulty: 1, hint: "Mail cover" },
	{ value: "Chair", category: "object", difficulty: 1, hint: "Seating" },
	{ value: "Table", category: "object", difficulty: 1, hint: "Surface" },
	{ value: "Cup", category: "object", difficulty: 1, hint: "Drink container" },
	{ value: "Plate", category: "object", difficulty: 1, hint: "Food holder" },
	{ value: "Book", category: "object", difficulty: 1, hint: "Reading material" },
	{ value: "Phone", category: "object", difficulty: 1, hint: "Communication device" },
	{ value: "Ball", category: "object", difficulty: 1, hint: "Round object for play" },
	{ value: "Pen", category: "object", difficulty: 1, hint: "Writing tool" },
	{ value: "Key", category: "object", difficulty: 1, hint: "Unlocking device" },
	{ value: "Glasses", category: "object", difficulty: 1, hint: "Eyewear" },
	{ value: "Camera", category: "object", difficulty: 1, hint: "Photography device" },
	{ value: "Clock", category: "object", difficulty: 1, hint: "Timekeeping device" },
	{ value: "Lamp", category: "object", difficulty: 1, hint: "Light source" },
	{ value: "Remote", category: "object", difficulty: 1, hint: "Control device" },
	{ value: "Candle", category: "object", difficulty: 1, hint: "Wax light" },
	{ value: "Brush", category: "object", difficulty: 1, hint: "Sweeping tool" },
	{ value: "Rope", category: "object", difficulty: 1, hint: "Twisted fiber" },
	{ value: "Scissors", category: "object", difficulty: 1, hint: "Cutting tool" },
	{ value: "Spoon", category: "object", difficulty: 1, hint: "Eating utensil" },
	{ value: "Fork", category: "object", difficulty: 1, hint: "Eating utensil" },
	{ value: "Knife", category: "object", difficulty: 1, hint: "Cutting utensil" },
	{ value: "Paper", category: "object", difficulty: 1, hint: "Writing material" },
	{ value: "Pillow", category: "object", difficulty: 1, hint: "Head support" },
	{ value: "Blanket", category: "object", difficulty: 1, hint: "Covering for warmth" },
	{ value: "Bottle", category: "object", difficulty: 1, hint: "Container with narrow neck" },
	{ value: "Cushion", category: "object", difficulty: 1, hint: "Soft support" },
	{ value: "Curtains", category: "object", difficulty: 1, hint: "Window coverings" },
	{ value: "Rug", category: "object", difficulty: 1, hint: "Floor covering" },
	{ value: "Guitar", category: "object", difficulty: 1, hint: "Stringed instrument" },
	{ value: "Violin", category: "object", difficulty: 2, hint: "Stringed instrument" },
	{ value: "Drum", category: "object", difficulty: 2, hint: "Percussion instrument" },
	{ value: "Trumpet", category: "object", difficulty: 2, hint: "Brass instrument" },
	{ value: "Piano", category: "object", difficulty: 1, hint: "Keyboard instrument" },
	{ value: "Microphone", category: "object", difficulty: 1, hint: "Sound input device" },
	{ value: "Speaker", category: "object", difficulty: 1, hint: "Sound output device" },
	{ value: "Headphones", category: "object", difficulty: 1, hint: "Sound output device" },
	{ value: "Sofa", category: "object", difficulty: 1, hint: "Seating" },
	{ value: "Armchair", category: "object", difficulty: 2, hint: "Seating with arms" },
	{ value: "Stool", category: "object", difficulty: 2, hint: "Seating without back" },
	{ value: "Desk", category: "object", difficulty: 1, hint: "Work surface" },
	{ value: "Drawer", category: "object", difficulty: 2, hint: "Storage compartment" },
	{ value: "Mirror", category: "object", difficulty: 1, hint: "Reflective surface" },
	{ value: "Toothbrush", category: "object", difficulty: 2, hint: "Dental hygiene tool" },
	{ value: "Toothpaste", category: "object", difficulty: 2, hint: "Dental hygiene product" },
	{ value: "Tissue", category: "object", difficulty: 2, hint: "Paper product" },
	{ value: "Soap", category: "object", difficulty: 2, hint: "Cleaning agent" },
	{ value: "Shampoo", category: "object", difficulty: 2, hint: "Hair cleansing product" },
	{ value: "Conditioner", category: "object", difficulty: 2, hint: "Hair care product" },
	{ value: "Toilet", category: "object", difficulty: 2, hint: "Sanitation fixture" },
	{ value: "Bathtub", category: "object", difficulty: 2, hint: "Bathing fixture" },
	{ value: "Shower", category: "object", difficulty: 2, hint: "Bathing fixture" },
	{ value: "Towel", category: "object", difficulty: 2, hint: "Drying cloth" },
	{ value: "Razor", category: "object", difficulty: 2, hint: "Shaving tool" },
	{ value: "Shaving Cream", category: "object", difficulty: 2, hint: "Shaving aid" },
	{ value: "Hairbrush", category: "object", difficulty: 2, hint: "Hair grooming tool" },
	{ value: "Comb", category: "object", difficulty: 2, hint: "Hair grooming tool" },
	{ value: "Perfume", category: "object", difficulty: 2, hint: "Fragrance" },
	{ value: "Deodorant", category: "object", difficulty: 2, hint: "Body odor blocker" },
	{ value: "Lotion", category: "object", difficulty: 2, hint: "Skin moisturizer" },
	{ value: "Makeup", category: "object", difficulty: 2, hint: "Cosmetic products" },
	{ value: "Foundation", category: "object", difficulty: 2, hint: "Base makeup" },
	{ value: "Lipstick", category: "object", difficulty: 2, hint: "Lip coloring" },
	{ value: "Eyeliner", category: "object", difficulty: 2, hint: "Eye defining product" },
	{ value: "Mascara", category: "object", difficulty: 2, hint: "Eye enhancing product" },
	{ value: "Eyeshadow", category: "object", difficulty: 2, hint: "Eye coloring product" },
	{ value: "Nail Polish", category: "object", difficulty: 2, hint: "Nail coloring product" },
	{ value: "Sunscreen", category: "object", difficulty: 2, hint: "Sun protection" },
	{ value: "Sunglasses", category: "object", difficulty: 2, hint: "Eye protection" },
	{ value: "Coat", category: "object", difficulty: 2, hint: "Outerwear" },
	{ value: "Jacket", category: "object", difficulty: 2, hint: "Outerwear" },
	{ value: "Sweater", category: "object", difficulty: 2, hint: "Warm top" },
	{ value: "T-shirt", category: "object", difficulty: 2, hint: "Casual top" },
	{ value: "Shirt", category: "object", difficulty: 2, hint: "Formal top" },
	{ value: "Dress", category: "object", difficulty: 2, hint: "Women's garment" },
	{ value: "Skirt", category: "object", difficulty: 2, hint: "Women's garment" },
	{ value: "Pants", category: "object", difficulty: 2, hint: "Bottoms" },
	{ value: "Shorts", category: "object", difficulty: 2, hint: "Bottoms" },
	{ value: "Jeans", category: "object", difficulty: 2, hint: "Casual pants" },
	{ value: "Sock", category: "object", difficulty: 2, hint: "Foot covering" },
	{ value: "Boot", category: "object", difficulty: 2, hint: "Footwear" },
	{ value: "Sandals", category: "object", difficulty: 2, hint: "Open-toed footwear" },
	{ value: "Sneakers", category: "object", difficulty: 2, hint: "Casual footwear" },
	{ value: "Slippers", category: "object", difficulty: 2, hint: "Indoor footwear" },
	{ value: "Bag", category: "object", difficulty: 2, hint: "Carrying item" },
	{ value: "Backpack", category: "object", difficulty: 2, hint: "Carrying item" },
	{ value: "Purse", category: "object", difficulty: 2, hint: "Women's bag" },
	{ value: "Wallet", category: "object", difficulty: 2, hint: "Money holder" },
	{ value: "Belt", category: "object", difficulty: 2, hint: "Waist accessory" },
	{ value: "Hat", category: "object", difficulty: 2, hint: "Headwear" },
	{ value: "Scarf", category: "object", difficulty: 2, hint: "Neckwear" },
	{ value: "Gloves", category: "object", difficulty: 2, hint: "Hand coverings" },
	{ value: "Tie", category: "object", difficulty: 2, hint: "Neckwear" },
	{ value: "Watch", category: "object", difficulty: 2, hint: "Wrist timepiece" },
	{ value: "Chainsaw", category: "object", difficulty: 3, hint: "Wood cutting tool" },
	{ value: "Chisel", category: "object", difficulty: 3, hint: "Wood shaping tool" },
	{ value: "Cocktail Shaker", category: "object", difficulty: 3, hint: "Drink mixer" },
	{ value: "Compass", category: "object", difficulty: 3, hint: "Directional tool" },
	{ value: "Corkscrew", category: "object", difficulty: 3, hint: "Bottle opener" },
	{ value: "Crowbar", category: "object", difficulty: 3, hint: "Prizing tool" },
	{ value: "Cutting Board", category: "object", difficulty: 3, hint: "Food prep surface" },
	{ value: "Dehumidifier", category: "object", difficulty: 3, hint: "Moisture remover" },
	{ value: "Diffuser", category: "object", difficulty: 3, hint: "Aromatherapy device" },
	{ value: "Disposable Camera", category: "object", difficulty: 3, hint: "One-time use photo device" },
	{ value: "Doorbell", category: "object", difficulty: 3, hint: "Visitor alert" },
	{ value: "Dough Roller", category: "object", difficulty: 3, hint: "Baking tool" },
	{ value: "Duct Tape", category: "object", difficulty: 3, hint: "Adhesive strip" },
	{ value: "Electric Mixer", category: "object", difficulty: 3, hint: "Food blending device" },
	{ value: "Fan", category: "object", difficulty: 3, hint: "Air circulation device" },
	{ value: "Fire Extinguisher", category: "object", difficulty: 3, hint: "Flame suppressor" },
	{ value: "Flashlight", category: "object", difficulty: 3, hint: "Portable light" },
	{ value: "Flask", category: "object", difficulty: 3, hint: "Portable drink container" },
	{ value: "Fly Swatter", category: "object", difficulty: 3, hint: "Insect control tool" },
	{ value: "Folding Chair", category: "object", difficulty: 3, hint: "Portable seating" },
	{ value: "Frying Pan", category: "object", difficulty: 3, hint: "Cooking pan" },
	{ value: "Funnel", category: "object", difficulty: 3, hint: "Liquid transfer tool" },
	{ value: "Garlic Press", category: "object", difficulty: 3, hint: "Garlic crushing tool" },
	{ value: "Grater", category: "object", difficulty: 3, hint: "Food shredding tool" },
	{ value: "Grill Pan", category: "object", difficulty: 3, hint: "Cooking pan" },
	{ value: "Hammer", category: "object", difficulty: 3, hint: "Nail-driving tool" },
	{ value: "Hand Mixer", category: "object", difficulty: 3, hint: "Handheld blending device" },
	{ value: "Hanger", category: "object", difficulty: 3, hint: "Clothing support" },
	{ value: "Headlamp", category: "object", difficulty: 3, hint: "Hands-free light" },
	{ value: "Ice Cream Scoop", category: "object", difficulty: 3, hint: "Frozen dessert tool" },
	{ value: "Ice Pick", category: "object", difficulty: 3, hint: "Ice breaking tool" },
	{ value: "Juicer", category: "object", difficulty: 3, hint: "Fruit squeezing tool" },
	{ value: "Ladle", category: "object", difficulty: 3, hint: "Soup serving tool" },
	{ value: "Laser Pointer", category: "object", difficulty: 3, hint: "Light projecting device" },
	{ value: "Lava Lamp", category: "object", difficulty: 3, hint: "Decorative lamp" },
	{ value: "Leather Jacket", category: "object", difficulty: 3, hint: "Outerwear" },
	{ value: "Letter Opener", category: "object", difficulty: 3, hint: "Envelope cutter" },
	{ value: "Light Bulb", category: "object", difficulty: 3, hint: "Illumination device" },
	{ value: "Loofah", category: "object", difficulty: 3, hint: "Shower scrubber" },
	{ value: "Magnifying Glass", category: "object", difficulty: 3, hint: "Small object viewer" },
	{ value: "Measuring Cup", category: "object", difficulty: 3, hint: "Volume measurement tool" },
	{ value: "Meat Tenderizer", category: "object", difficulty: 3, hint: "Muscle relaxing tool" },
	{ value: "Mixing Bowl", category: "object", difficulty: 3, hint: "Ingredient blending container" },
	{ value: "Mop", category: "object", difficulty: 3, hint: "Floor cleaner" },
	{ value: "Nail File", category: "object", difficulty: 3, hint: "Manicure tool" },
	{ value: "Nutcracker", category: "object", difficulty: 3, hint: "Shell cracking tool" },
	{ value: "Oven Mitt", category: "object", difficulty: 3, hint: "Baking protection" },
	{ value: "Pasta Maker", category: "object", difficulty: 3, hint: "Noodle creator" },
	{ value: "Pencil Sharpener", category: "object", difficulty: 3, hint: "Writing tool sharpener" },
	{ value: "Pet Carrier", category: "object", difficulty: 3, hint: "Animal transporter" },
	{ value: "Plunger", category: "object", difficulty: 3, hint: "Pipe unclogger" },
	{ value: "Potato Peeler", category: "object", difficulty: 3, hint: "Skin removal tool" },
	{ value: "Protractor", category: "object", difficulty: 3, hint: "Angle measurement tool" },
	{ value: "Rubber Bands", category: "object", difficulty: 3, hint: "Flexible loop" },
	{ value: "Sandpaper", category: "object", difficulty: 3, hint: "Abrasive material" },
	{ value: "Screwdriver", category: "object", difficulty: 3, hint: "Screw turning tool" },
	{ value: "Shoe Horn", category: "object", difficulty: 3, hint: "Footwear aid" },
	{ value: "Shovel", category: "object", difficulty: 3, hint: "Digging tool" },
	{ value: "Silicone Spatula", category: "object", difficulty: 3, hint: "Flexible cooking tool" },
	{ value: "Sink Strainer", category: "object", difficulty: 3, hint: "Drain filter" },
	{ value: "Skewers", category: "object", difficulty: 3, hint: "Food piercing tool" },
	{ value: "Slotted Spoon", category: "object", difficulty: 3, hint: "Serving utensil" },
	{ value: "Spatula", category: "object", difficulty: 3, hint: "Cooking tool" },
	{ value: "Squeegee", category: "object", difficulty: 3, hint: "Glass cleaner" },
	{ value: "Steam Iron", category: "object", difficulty: 3, hint: "Wrinkle remover" },
	{ value: "Stethoscope", category: "object", difficulty: 3, hint: "Listening device" },
	{ value: "Stirring Spoon", category: "object", difficulty: 3, hint: "Mixing utensil" },
	{ value: "Strainer", category: "object", difficulty: 3, hint: "Liquid separator" },
	{ value: "Tape Measure", category: "object", difficulty: 3, hint: "Length measuring tool" },
	{ value: "Thermometer", category: "object", difficulty: 3, hint: "Temperature gauge" },
	{ value: "Timer", category: "object", difficulty: 3, hint: "Clock substitute" },
	{ value: "Tongs", category: "object", difficulty: 3, hint: "Grabbing utensil" },
	{ value: "Toothpicks", category: "object", difficulty: 3, hint: "Food cleaning tool" },
	{ value: "Trash Bags", category: "object", difficulty: 3, hint: "Waste container liner" },
	{ value: "Umbrella Stand", category: "object", difficulty: 3, hint: "Rain protection storage" },
];

export default items;
