import type { ICategoryWord } from "../api/items/words.get";

const items: ICategoryWord[] = [
	{ value: "Titanic", difficulty: 1, hint: "Ship disaster", category: "movie" },
	{ value: "Jurassic Park", difficulty: 1, hint: "Dinosaur theme park", category: "movie" },
	{ value: "Forrest Gump", difficulty: 1, hint: "Life is like a box of chocolates", category: "movie" },
	{ value: "Finding Nemo", difficulty: 1, hint: "Lost fish", category: "movie" },
	{ value: "Toy Story", difficulty: 1, hint: "Animated toys", category: "movie" },
	{ value: "The Lion King", difficulty: 1, hint: "Hakuna Matata", category: "movie" },
	{ value: "Frozen", difficulty: 1, hint: "Let it go", category: "movie" },
	{ value: "Aladdin", difficulty: 1, hint: "Magic carpet ride", category: "movie" },
	{ value: "Shrek", difficulty: 1, hint: "Ogre adventure", category: "movie" },
	{ value: "The Incredibles", difficulty: 1, hint: "Superhero family", category: "movie" },
	{ value: "Home Alone", difficulty: 1, hint: "Kevin's Christmas", category: "movie" },
	{ value: "The Wizard of Oz", difficulty: 1, hint: "Yellow brick road", category: "movie" },
	{ value: "Harry Potter", difficulty: 1, hint: "Boy wizard", category: "movie" },
	{ value: "Avatar", difficulty: 1, hint: "Blue aliens", category: "movie" },
	{ value: "The Avengers", difficulty: 1, hint: "Marvel superheroes", category: "movie" },
	{ value: "Pirates of the Caribbean", difficulty: 1, hint: "Captain Jack Sparrow", category: "movie" },
	{ value: "Indiana Jones", difficulty: 1, hint: "Archaeologist adventurer", category: "movie" },
	{ value: "The Matrix", difficulty: 1, hint: "Red pill, blue pill", category: "movie" },
	{ value: "Star Wars", difficulty: 1, hint: "May the Force be with you", category: "movie" },
	{ value: "Back to the Future", difficulty: 1, hint: "Time-traveling DeLorean", category: "movie" },
	{ value: "Ghostbusters", difficulty: 1, hint: "Who you gonna call?", category: "movie" },
	{ value: "Jaws", difficulty: 1, hint: "Giant shark", category: "movie" },
	{ value: "The Godfather", difficulty: 1, hint: "Don Vito Corleone", category: "movie" },
	{ value: "Rocky", difficulty: 1, hint: "Boxer underdog", category: "movie" },
	{ value: "Spider-Man", difficulty: 1, hint: "Friendly neighborhood", category: "movie" },
	{ value: "Transformers", difficulty: 1, hint: "Robots in disguise", category: "movie" },
	{ value: "Batman", difficulty: 1, hint: "Gotham's dark knight", category: "movie" },
	{ value: "Superman", difficulty: 1, hint: "Man of steel", category: "movie" },
	{ value: "Die Hard", difficulty: 1, hint: "Yippee-ki-yay", category: "movie" },
	{ value: "Terminator", difficulty: 1, hint: "I'll be back", category: "movie" },
	{ value: "The Terminator", difficulty: 1, hint: "Cyborg assassin", category: "movie" },
	{ value: "The Dark Knight", difficulty: 1, hint: "Joker's nemesis", category: "movie" },
	{ value: "The Lord of the Rings", difficulty: 1, hint: "One ring to rule them all", category: "movie" },
	{ value: "The Shawshank Redemption", difficulty: 1, hint: "Andy's escape", category: "movie" },
	{ value: "The Sixth Sense", difficulty: 1, hint: "I see dead people", category: "movie" },
	{ value: "The Green Mile", difficulty: 1, hint: "Death row miracles", category: "movie" },
	{ value: "The Silence of the Lambs", difficulty: 1, hint: "Hannibal Lecter", category: "movie" },
	{ value: "The Usual Suspects", difficulty: 1, hint: "Keyser Söze", category: "movie" },
	{ value: "Goodfellas", difficulty: 1, hint: "Wiseguy life", category: "movie" },
	{ value: "Schindler's List", difficulty: 1, hint: "Oskar Schindler", category: "movie" },
	{ value: "The Pianist", difficulty: 1, hint: "Warsaw pianist", category: "movie" },
	{ value: "Saving Private Ryan", difficulty: 1, hint: "D-Day rescue", category: "movie" },
	{ value: "The Deer Hunter", difficulty: 1, hint: "Russian roulette", category: "movie" },
	{ value: "The Hurt Locker", difficulty: 1, hint: "Bomb disposal", category: "movie" },
	{ value: "American Sniper", difficulty: 1, hint: "Chris Kyle's story", category: "movie" },
	{ value: "Platoon", difficulty: 1, hint: "Vietnam War", category: "movie" },
	{ value: "Apocalypse Now", difficulty: 1, hint: "Ride of the Valkyries", category: "movie" },
	{ value: "Full Metal Jacket", difficulty: 1, hint: "Gunnery Sergeant Hartman", category: "movie" },
	{ value: "Black Hawk Down", difficulty: 1, hint: "Battle of Mogadishu", category: "movie" },
	{ value: "Das Boot", difficulty: 1, hint: "German U-boat", category: "movie" },
	{ value: "Casablanca", difficulty: 1, hint: "Here's looking at you, kid", category: "movie" },
	{ value: "Gone with the Wind", difficulty: 1, hint: "Frankly, my dear...", category: "movie" },
	{ value: "The Sound of Music", difficulty: 1, hint: "Hills are alive", category: "movie" },
	{ value: "Lawrence of Arabia", difficulty: 1, hint: "Desert epic", category: "movie" },
	{ value: "Ben-Hur", difficulty: 1, hint: "Chariot race", category: "movie" },
	{ value: "The Bridge on the River Kwai", difficulty: 1, hint: "Whistling tune", category: "movie" },
	{ value: "Doctor Zhivago", difficulty: 1, hint: "Russian romance", category: "movie" },
	{ value: "Spartacus", difficulty: 1, hint: "I am Spartacus", category: "movie" },
	{ value: "Gandhi", difficulty: 1, hint: "Non-violence leader", category: "movie" },
	{ value: "Amadeus", difficulty: 1, hint: "Mozart's rival", category: "movie" },
	{ value: "Gladiator", difficulty: 1, hint: "Are you not entertained?", category: "movie" },
	{ value: "The Last Samurai", difficulty: 1, hint: "Tom Cruise in Japan", category: "movie" },
	{ value: "Troy", difficulty: 1, hint: "Brad Pitt's Achilles", category: "movie" },
	{ value: "300", difficulty: 1, hint: "This is Sparta!", category: "movie" },
	{ value: "Braveheart", difficulty: 1, hint: "Freedom!", category: "movie" },
	{ value: "Kingdom of Heaven", difficulty: 1, hint: "Crusades epic", category: "movie" },
	{ value: "Apocalypto", difficulty: 1, hint: "Mayan adventure", category: "movie" },
	{ value: "Alexander", difficulty: 1, hint: "Macedonian conqueror", category: "movie" },
	{ value: "The Patriot", difficulty: 1, hint: "Mel Gibson's Revolutionary", category: "movie" },
	{ value: "Robin Hood", difficulty: 1, hint: "Steals from the rich", category: "movie" },
	{ value: "Monty Python and the Holy Grail", difficulty: 1, hint: "Silly Knights", category: "movie" },
	{ value: "Life of Brian", difficulty: 1, hint: "He's not the Messiah", category: "movie" },
	{ value: "The Meaning of Life", difficulty: 1, hint: "Philosophical comedy", category: "movie" },
	{ value: "Annie Hall", difficulty: 1, hint: "Woody Allen romance", category: "movie" },
	{ value: "Manhattan", difficulty: 1, hint: "New York love story", category: "movie" },
	{ value: "Sleeper", difficulty: 1, hint: "Woody Allen futuristic", category: "movie" },
	{ value: "Hannah and Her Sisters", difficulty: 1, hint: "Family drama", category: "movie" },
	{ value: "Crimes and Misdemeanors", difficulty: 1, hint: "Morality tale", category: "movie" },
	{ value: "Zelig", difficulty: 1, hint: "Chameleon man", category: "movie" },
	{ value: "The Purple Rose of Cairo", difficulty: 1, hint: "Movie magic", category: "movie" },
	{ value: "Stardust Memories", difficulty: 1, hint: "Woody Allen's reflections", category: "movie" },
	{ value: "Interiors", difficulty: 1, hint: "Dysfunctional family", category: "movie" },
	{ value: "Broadway Danny Rose", difficulty: 1, hint: "Small-time manager", category: "movie" },
	{ value: "Radio Days", difficulty: 1, hint: "Golden age of radio", category: "movie" },
	{ value: "Another Woman", difficulty: 1, hint: "Woody Allen drama", category: "movie" },
	{ value: "Shadows and Fog", difficulty: 1, hint: "Mysterious murders", category: "movie" },
	{ value: "Sweet and Lowdown", difficulty: 1, hint: "Jazz guitarist", category: "movie" },
	{ value: "Celebrity", difficulty: 1, hint: "Fame and fortune", category: "movie" },
	{ value: "Inglourious Basterds", difficulty: 2, hint: "WWII revenge", category: "movie" },
	{ value: "Pulp Fiction", difficulty: 2, hint: "Tarantino classic", category: "movie" },
	{ value: "The Shining", difficulty: 2, hint: "Here's Johnny!", category: "movie" },
	{ value: "Scarface", difficulty: 2, hint: "Say hello to my little friend", category: "movie" },
	{ value: "Reservoir Dogs", difficulty: 2, hint: "Diamond heist gone wrong", category: "movie" },
	{ value: "A Clockwork Orange", difficulty: 2, hint: "Ultra-violence", category: "movie" },
	{ value: "Good Will Hunting", difficulty: 2, hint: "Math genius janitor", category: "movie" },
	{ value: "The Grand Budapest Hotel", difficulty: 2, hint: "Wes Anderson's hotel", category: "movie" },
	{ value: "No Country for Old Men", difficulty: 2, hint: "Chigurh's coin", category: "movie" },
	{ value: "The Big Lebowski", difficulty: 2, hint: "The Dude abides", category: "movie" },
	{ value: "Fargo", difficulty: 2, hint: "Wood chipper", category: "movie" },
	{ value: "There Will Be Blood", difficulty: 2, hint: "I drink your milkshake", category: "movie" },
	{ value: "The Prestige", difficulty: 2, hint: "Magic rivalry", category: "movie" },
	{ value: "Drive", difficulty: 2, hint: "Ryan Gosling's getaway", category: "movie" },
	{ value: "American Psycho", difficulty: 2, hint: "Patrick Bateman", category: "movie" },
	{ value: "Memento", difficulty: 2, hint: "Memory loss thriller", category: "movie" },
	{ value: "Eternal Sunshine of the Spotless Mind", difficulty: 2, hint: "Memory erasure", category: "movie" },
	{ value: "The Truman Show", difficulty: 2, hint: "Reality TV life", category: "movie" },
	{ value: "Lost in Translation", difficulty: 2, hint: "Bill Murray in Japan", category: "movie" },
	{ value: "The Royal Tenenbaums", difficulty: 2, hint: "Quirky family", category: "movie" },
	{ value: "The Life Aquatic with Steve Zissou", difficulty: 2, hint: "Underwater adventure", category: "movie" },
	{ value: "Moonrise Kingdom", difficulty: 2, hint: "Young love", category: "movie" },
	{ value: "Fantastic Mr. Fox", difficulty: 2, hint: "Stop-motion animals", category: "movie" },
	{ value: "Birdman", difficulty: 2, hint: "Single-shot superhero", category: "movie" },
	{ value: "Ratatouille", difficulty: 2, hint: "Cooking rat", category: "movie" },
	{ value: "WALL-E", difficulty: 2, hint: "Lonely robot", category: "movie" },
	{ value: "Up", difficulty: 2, hint: "Floating house", category: "movie" },
	{ value: "Inside Out", difficulty: 2, hint: "Emotions adventure", category: "movie" },
	{ value: "Toy Story 3", difficulty: 2, hint: "Andy's college", category: "movie" },
	{ value: "Finding Dory", difficulty: 2, hint: "Forgetful fish", category: "movie" },
	{ value: "Coco", difficulty: 2, hint: "Day of the Dead", category: "movie" },
	{ value: "Soul", difficulty: 2, hint: "Life before life", category: "movie" },
	{ value: "The Social Network", difficulty: 2, hint: "Facebook's beginnings", category: "movie" },
	{ value: "Moneyball", difficulty: 2, hint: "Baseball statistics", category: "movie" },
	{ value: "Catch Me If You Can", difficulty: 2, hint: "Frank Abagnale Jr.", category: "movie" },
	{ value: "Inception", difficulty: 2, hint: "Dream within a dream", category: "movie" },
	{ value: "Interstellar", difficulty: 2, hint: "Space-time adventure", category: "movie" },
	{ value: "Dunkirk", difficulty: 2, hint: "Evacuation of Allied soldiers", category: "movie" },
	{ value: "The Dark Knight Rises", difficulty: 2, hint: "Batman's final act", category: "movie" },
	{ value: "Tenet", difficulty: 2, hint: "Time inversion", category: "movie" },
	{ value: "Fight Club", difficulty: 2, hint: "First rule of fight club", category: "movie" },
	{ value: "Se7en", difficulty: 2, hint: "Seven deadly sins", category: "movie" },
	{ value: "Gone Girl", difficulty: 2, hint: "Missing wife", category: "movie" },
	{ value: "The Girl with the Dragon Tattoo", difficulty: 2, hint: "Lisbeth Salander", category: "movie" },
	{ value: "Zodiac", difficulty: 2, hint: "Unsolved murders", category: "movie" },
	{ value: "The Curious Case of Benjamin Button", difficulty: 2, hint: "Reverse aging", category: "movie" },
	{ value: "The Game", difficulty: 2, hint: "Mind-bending thriller", category: "movie" },
	{ value: "Mystic River", difficulty: 2, hint: "Childhood tragedy", category: "movie" },
	{ value: "Taxi Driver", difficulty: 2, hint: "You talking to me?", category: "movie" },
	{ value: "Raging Bull", difficulty: 2, hint: "Jake LaMotta", category: "movie" },
	{ value: "Mean Streets", difficulty: 2, hint: "Scorsese's early work", category: "movie" },
	{ value: "The King of Comedy", difficulty: 2, hint: "Rupert Pupkin", category: "movie" },
	{ value: "The Age of Innocence", difficulty: 2, hint: "Edith Wharton", category: "movie" },
	{ value: "The Aviator", difficulty: 2, hint: "Howard Hughes", category: "movie" },
	{ value: "Casino", difficulty: 2, hint: "Ace Rothstein", category: "movie" },
	{ value: "The Departed", difficulty: 2, hint: "Undercover cops", category: "movie" },
	{ value: "Gangs of New York", difficulty: 2, hint: "Civil War gangs", category: "movie" },
	{ value: "The Irishman", difficulty: 2, hint: "Jimmy Hoffa", category: "movie" },
	{ value: "The Wolf of Wall Street", difficulty: 2, hint: "Jordan Belfort", category: "movie" },
	{ value: "Elephant Man", difficulty: 3, hint: "John Merrick", category: "movie" },
	{ value: "Mulholland Drive", difficulty: 3, hint: "Hollywood nightmare", category: "movie" },
	{ value: "Lost Highway", difficulty: 3, hint: "Mind-bending road", category: "movie" },
	{ value: "Blue Velvet", difficulty: 3, hint: "Lynchian suburbia", category: "movie" },
	{ value: "Inland Empire", difficulty: 3, hint: "Lynchian labyrinth", category: "movie" },
	{ value: "Twin Peaks: Fire Walk with Me", difficulty: 3, hint: "Laura Palmer's tale", category: "movie" },
	{ value: "Wild at Heart", difficulty: 3, hint: "Lovers on the run", category: "movie" },
	{ value: "The Elephant Man", difficulty: 3, hint: "John Merrick", category: "movie" },
	{ value: "Dune", difficulty: 3, hint: "Sci-fi sandworms", category: "movie" },
	{ value: "The Straight Story", difficulty: 3, hint: "Elderly man's journey", category: "movie" },
	{ value: "Eraserhead", difficulty: 3, hint: "Man with odd baby", category: "movie" },
];

export default items;
