import type { ICategoryWord } from "../api/items/words.get";

const items: ICategoryWord[] = [
	{ value: "Albert Einstein", category: "person", difficulty: 1, hint: "Theory of Relativity" },
	{ value: "Oprah Winfrey", category: "person", difficulty: 1, hint: "Media Mogul and Philanthropist" },
	{ value: "Michael Jordan", category: "person", difficulty: 1, hint: "Basketball Legend" },
	{ value: "Elvis Presley", category: "person", difficulty: 1, hint: "King of Rock and Roll" },
	{ value: "Walt Disney", category: "person", difficulty: 1, hint: "Creator of Mickey Mouse" },
	{ value: "Marilyn Monroe", category: "person", difficulty: 1, hint: "Iconic Actress" },
	{ value: "Martin Luther King Jr.", category: "person", difficulty: 1, hint: "Civil Rights Leader" },
	{ value: "Steve Jobs", category: "person", difficulty: 1, hint: "Co-founder of Apple Inc." },
	{ value: "Mother Teresa", category: "person", difficulty: 1, hint: "Nun and Humanitarian" },
	{ value: "Mahatma Gandhi", category: "person", difficulty: 1, hint: "Leader of Indian Independence Movement" },
	{ value: "Princess Diana", category: "person", difficulty: 1, hint: "Former Princess of Wales" },
	{ value: "Leonardo da Vinci", category: "person", difficulty: 1, hint: "Renaissance Artist and Inventor" },
	{ value: "Beethoven", category: "person", difficulty: 1, hint: "Classical Composer" },
	{ value: "Vincent van Gogh", category: "person", difficulty: 1, hint: "Post-Impressionist Painter" },
	{ value: "William Shakespeare", category: "person", difficulty: 1, hint: "Renowned Playwright" },
	{ value: "Charles Darwin", category: "person", difficulty: 1, hint: "Theory of Evolution" },
	{ value: "Marie Curie", category: "person", difficulty: 1, hint: "Nobel Prize-winning Physicist and Chemist" },
	{ value: "Alexander Graham Bell", category: "person", difficulty: 1, hint: "Inventor of the Telephone" },
	{ value: "Amelia Earhart", category: "person", difficulty: 1, hint: "Aviation Pioneer" },
	{ value: "Pablo Picasso", category: "person", difficulty: 1, hint: "Cubist Painter" },
	{ value: "Coco Chanel", category: "person", difficulty: 1, hint: "Fashion Designer" },
	{ value: "Frida Kahlo", category: "person", difficulty: 1, hint: "Mexican Artist" },
	{ value: "Queen Elizabeth II", category: "person", difficulty: 1, hint: "Longest-reigning Current Monarch" },
	{ value: "Albert Schweitzer", category: "person", difficulty: 1, hint: "Philosopher and Humanitarian" },
	{ value: "Napoleon Bonaparte", category: "person", difficulty: 1, hint: "French Military Leader" },
	{ value: "Henry Ford", category: "person", difficulty: 1, hint: "Founder of Ford Motor Company" },
	{ value: "Rosa Parks", category: "person", difficulty: 1, hint: "Civil Rights Activist" },
	{ value: "Christopher Columbus", category: "person", difficulty: 1, hint: "Explorer" },
	{ value: "Neil Armstrong", category: "person", difficulty: 1, hint: "First Person to Walk on the Moon" },
	{ value: "J.K. Rowling", category: "person", difficulty: 1, hint: "Author of Harry Potter Series" },
	{ value: "Elon Musk", category: "person", difficulty: 1, hint: "Entrepreneur and CEO of SpaceX and Tesla" },
	{ value: "Stephen Hawking", category: "person", difficulty: 1, hint: "Theoretical Physicist and Cosmologist" },
	{ value: "Ellen DeGeneres", category: "person", difficulty: 1, hint: "Comedian and Talk Show Host" },
	{ value: "Stephen King", category: "person", difficulty: 1, hint: "Author of Horror Novels" },
	{ value: "Tom Hanks", category: "person", difficulty: 1, hint: "Award-winning Actor" },
	{ value: "Dwayne Johnson", category: "person", difficulty: 1, hint: "Actor and Former Wrestler" },
	{ value: "Beyoncé", category: "person", difficulty: 1, hint: "Singer and Actress" },
	{ value: "Taylor Swift", category: "person", difficulty: 1, hint: "Singer-songwriter" },
	{ value: "Adele", category: "person", difficulty: 1, hint: "Singer-songwriter" },
	{ value: "Lionel Messi", category: "person", difficulty: 1, hint: "Footballer" },
	{ value: "Cristiano Ronaldo", category: "person", difficulty: 1, hint: "Footballer" },
	{ value: "Usain Bolt", category: "person", difficulty: 1, hint: "Sprinter" },
	{ value: "Michael Phelps", category: "person", difficulty: 1, hint: "Swimmer" },
	{ value: "Roger Federer", category: "person", difficulty: 1, hint: "Tennis Player" },
	{ value: "Rafael Nadal", category: "person", difficulty: 1, hint: "Tennis Player" },
	{ value: "Novak Djokovic", category: "person", difficulty: 1, hint: "Tennis Player" },
	{ value: "Simone Biles", category: "person", difficulty: 1, hint: "Artistic Gymnast" },
	{ value: "LeBron James", category: "person", difficulty: 1, hint: "Basketball Player" },
	{ value: "Kobe Bryant", category: "person", difficulty: 1, hint: "Basketball Legend" },
	{ value: "Venus Williams", category: "person", difficulty: 1, hint: "Tennis Player" },
	{ value: "Maria Sharapova", category: "person", difficulty: 1, hint: "Tennis Player" },
	{ value: "Bill Gates", category: "person", difficulty: 1, hint: "Co-founder of Microsoft" },
	{ value: "Mark Zuckerberg", category: "person", difficulty: 1, hint: "Co-founder of Facebook" },
	{ value: "Warren Buffett", category: "person", difficulty: 1, hint: "Investor and Business Tycoon" },
	{ value: "Larry Page", category: "person", difficulty: 1, hint: "Co-founder of Google" },
	{ value: "Sergey Brin", category: "person", difficulty: 1, hint: "Co-founder of Google" },
	{ value: "Larry Ellison", category: "person", difficulty: 1, hint: "Co-founder of Oracle Corporation" },
	{ value: "Jack Ma", category: "person", difficulty: 1, hint: "Co-founder of Alibaba Group" },
	{ value: "Marie Antoinette", category: "person", difficulty: 2, hint: "Last Queen of France" },
	{ value: "Leon Trotsky", category: "person", difficulty: 2, hint: "Russian Revolutionary" },
	{ value: "Vladimir Lenin", category: "person", difficulty: 2, hint: "Russian Revolutionary" },
	{ value: "Joseph Stalin", category: "person", difficulty: 2, hint: "Soviet Leader" },
	{ value: "Adolf Hitler", category: "person", difficulty: 2, hint: "Nazi Leader" },
	{ value: "Nikola Tesla", category: "person", difficulty: 2, hint: "Inventor and Electrical Engineer" },
	{ value: "Henry VIII", category: "person", difficulty: 2, hint: "King of England" },
	{ value: "Cleopatra", category: "person", difficulty: 2, hint: "Queen of Egypt" },
	{ value: "Julius Caesar", category: "person", difficulty: 2, hint: "Roman Emperor" },
	{ value: "Alexander the Great", category: "person", difficulty: 2, hint: "Ancient Macedonian King" },
	{ value: "Genghis Khan", category: "person", difficulty: 2, hint: "Founder of the Mongol Empire" },
	{ value: "Attila the Hun", category: "person", difficulty: 2, hint: "Leader of the Hunnic Empire" },
	{ value: "Queen Elizabeth I", category: "person", difficulty: 2, hint: "Virgin Queen" },
	{ value: "George Washington", category: "person", difficulty: 2, hint: "First President of the United States" },
	{ value: "Thomas Jefferson", category: "person", difficulty: 2, hint: "Author of the Declaration of Independence" },
	{ value: "Benjamin Franklin", category: "person", difficulty: 2, hint: "Founding Father of the United States" },
	{ value: "Abraham Lincoln", category: "person", difficulty: 2, hint: "16th President of the United States" },
	{ value: "John F. Kennedy", category: "person", difficulty: 2, hint: "35th President of the United States" },
	{ value: "Franklin D. Roosevelt", category: "person", difficulty: 2, hint: "32nd President of the United States" },
	{ value: "Winston Churchill", category: "person", difficulty: 2, hint: "British Prime Minister during WWII" },
	{ value: "Mao Zedong", category: "person", difficulty: 2, hint: "Chinese Communist Leader" },
	{ value: "Ho Chi Minh", category: "person", difficulty: 2, hint: "Vietnamese Communist Leader" },
	{ value: "Margaret Thatcher", category: "person", difficulty: 2, hint: "British Prime Minister" },
	{ value: "Queen Victoria", category: "person", difficulty: 2, hint: "Longest-reigning British Monarch" },
	{ value: "Ronald Reagan", category: "person", difficulty: 2, hint: "40th President of the United States" },
	{ value: "Mikhail Gorbachev", category: "person", difficulty: 2, hint: "Last Leader of the Soviet Union" },
	{ value: "Fidel Castro", category: "person", difficulty: 2, hint: "Cuban Revolutionary Leader" },
	{ value: "Saddam Hussein", category: "person", difficulty: 2, hint: "Former President of Iraq" },
	{ value: "Muammar Gaddafi", category: "person", difficulty: 2, hint: "Former Leader of Libya" },
	{ value: "Nelson Mandela", category: "person", difficulty: 2, hint: "Anti-Apartheid Activist" },
	{ value: "Vladimir Putin", category: "person", difficulty: 2, hint: "President of Russia" },
	{ value: "Barack Obama", category: "person", difficulty: 2, hint: "44th President of the United States" },
	{ value: "George W. Bush", category: "person", difficulty: 2, hint: "43rd President of the United States" },
	{ value: "Bill Clinton", category: "person", difficulty: 2, hint: "42nd President of the United States" },
	{ value: "Donald Trump", category: "person", difficulty: 2, hint: "45th President of the United States" },
	{ value: "Joe Biden", category: "person", difficulty: 2, hint: "46th President of the United States" },
	{ value: "Elizabeth Warren", category: "person", difficulty: 2, hint: "American Politician and Senator" },
	{ value: "Kamala Harris", category: "person", difficulty: 2, hint: "Vice President of the United States" },
	{ value: "Hillary Clinton", category: "person", difficulty: 2, hint: "Former First Lady" },
	{ value: "Michelle Obama", category: "person", difficulty: 2, hint: "Former First Lady" },
	{ value: "Nancy Pelosi", category: "person", difficulty: 2, hint: "Speaker of the House" },
	{ value: "Mitch McConnell", category: "person", difficulty: 2, hint: "Senate Minority Leader" },
	{ value: "Bernie Sanders", category: "person", difficulty: 2, hint: "American Politician and Senator" },
	{ value: "George Soros", category: "person", difficulty: 2, hint: "Investor and Philanthropist" },
	{ value: "Jeff Bezos", category: "person", difficulty: 2, hint: "Founder of Amazon" },
	{ value: "Jack Dorsey", category: "person", difficulty: 2, hint: "Co-founder of Twitter" },
	{ value: "Tim Cook", category: "person", difficulty: 2, hint: "CEO of Apple Inc." },
	{ value: "Satya Nadella", category: "person", difficulty: 2, hint: "CEO of Microsoft" },
	{ value: "Reed Hastings", category: "person", difficulty: 2, hint: "Co-founder of Netflix" },
	{ value: "Richard Branson", category: "person", difficulty: 2, hint: "Founder of Virgin Group" },
	{ value: "Michael Dell", category: "person", difficulty: 2, hint: "Founder of Dell Technologies" },
	{ value: "Masayoshi Son", category: "person", difficulty: 2, hint: "CEO of SoftBank" },
	{ value: "Sir Isaac Newton", category: "person", difficulty: 3, hint: "Laws of Motion and Gravity" },
	{ value: "Galileo Galilei", category: "person", difficulty: 3, hint: "Astronomer and Physicist" },
	{ value: "Johannes Kepler", category: "person", difficulty: 3, hint: "Planetary Motion" },
	{ value: "Rene Descartes", category: "person", difficulty: 3, hint: "Cartesian Dualism" },
	{ value: "John Locke", category: "person", difficulty: 3, hint: "Philosopher and Political Theorist" },
	{ value: "David Hume", category: "person", difficulty: 3, hint: "Empiricist Philosopher" },
	{ value: "Immanuel Kant", category: "person", difficulty: 3, hint: "Philosopher of Enlightenment" },
	{ value: "Georg Wilhelm Friedrich Hegel", category: "person", difficulty: 3, hint: "German Idealist Philosopher" },
	{ value: "Arthur Schopenhauer", category: "person", difficulty: 3, hint: "Philosopher of Pessimism" },
	{ value: "Friedrich Nietzsche", category: "person", difficulty: 3, hint: "Philosopher and Critic of Culture" },
	{ value: "Sigmund Freud", category: "person", difficulty: 3, hint: "Founder of Psychoanalysis" },
	{ value: "Jean-Paul Sartre", category: "person", difficulty: 3, hint: "Existentialist Philosopher" },
	{ value: "Albert Camus", category: "person", difficulty: 3, hint: "Absurdist Philosopher" },
	{ value: "Thomas Aquinas", category: "person", difficulty: 3, hint: "Theologian and Philosopher" },
	{ value: "John Calvin", category: "person", difficulty: 3, hint: "Protestant Reformer" },
	{ value: "Martin Luther", category: "person", difficulty: 3, hint: "Protestant Reformer" },
	{ value: "John Wesley", category: "person", difficulty: 3, hint: "Founder of Methodism" },
	{ value: "John Knox", category: "person", difficulty: 3, hint: "Scottish Reformer" },
	{ value: "Pope John Paul II", category: "person", difficulty: 3, hint: "Catholic Pope" },
	{ value: "Billy Graham", category: "person", difficulty: 3, hint: "Evangelist Preacher" },
	{ value: "Rick Warren", category: "person", difficulty: 3, hint: "Author of 'The Purpose Driven Life'" },
	{ value: "Joel Osteen", category: "person", difficulty: 3, hint: "Televangelist" },
	{ value: "C.S. Lewis", category: "person", difficulty: 3, hint: "Author of 'The Chronicles of Narnia'" },
	{ value: "G.K. Chesterton", category: "person", difficulty: 3, hint: "Writer and Philosopher" },
	{ value: "Dietrich Bonhoeffer", category: "person", difficulty: 3, hint: "German Theologian and Anti-Nazi Dissident" },
	{ value: "Karl Barth", category: "person", difficulty: 3, hint: "Swiss Reformed Theologian" },
	{ value: "John Henry Newman", category: "person", difficulty: 3, hint: "Cardinal and Theologian" },
	{ value: "Charles Spurgeon", category: "person", difficulty: 3, hint: "English Particular Baptist Preacher" },
	{ value: "Jonathan Edwards", category: "person", difficulty: 3, hint: "American Revivalist Preacher" },
	{ value: "John Piper", category: "person", difficulty: 3, hint: "Reformed Baptist Preacher" },
	{ value: "Tim Keller", category: "person", difficulty: 3, hint: "Presbyterian Minister" },
	{ value: "R.C. Sproul", category: "person", difficulty: 3, hint: "Reformed Theologian and Author" },
];

export default items;
